PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE `business_pages` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`slug` text NOT NULL,
	`owner_id` text NOT NULL,
	`category_id` text,
	`entity_type` text DEFAULT 'business',
	`status` text DEFAULT 'draft',
	`banner_image_id` text,
	`profile_image_id` text,
	`contact_name` text,
	`contact_number` text,
	`country_code` text DEFAULT '+670',
	`year_of_establishment` integer,
	`email` text,
	`address` text,
	`location_lat` real,
	`location_lng` real,
	`opening_hours` text,
	`about_us` text,
	`latest_updates` text,
	`tags` text,
	`industry` text,
	`likes` integer DEFAULT 0,
	`saves` integer DEFAULT 0,
	`rating_average` real DEFAULT 0,
	`rating_count` integer DEFAULT 0,
	`views` integer DEFAULT 0,
	`plan_type` text,
	`publish_date` integer,
	`expiry_date` integer,
	`registration_url` text,
	`verified_badge` integer DEFAULT false,
	`social_links` text,
	`photo_gallery` text,
	`latest_update` text,
	`latest_update_images` text,
	`latest_update_date` integer,
	`created_at` integer DEFAULT (strftime('%s', 'now')),
	`updated_at` integer DEFAULT (strftime('%s', 'now'))
, organization_type text, subscription_status TEXT DEFAULT 'none', grace_period_end_date INTEGER);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-1','Café Timor','cafe-timor','user-1','cat-1','business','live',NULL,NULL,'João Silva','77001234','+670',NULL,'info@cafetimor.tl','Avenida de绍兴, Dili',-8.5569,125.5603,'{"monday":{"open":"07:00","close":"22:00"},"tuesday":{"open":"07:00","close":"22:00"},"wednesday":{"open":"07:00","close":"22:00"},"thursday":{"open":"07:00","close":"22:00"},"friday":{"open":"07:00","close":"23:00"},"saturday":{"open":"08:00","close":"23:00"},"sunday":{"open":"08:00","close":"20:00"}}','Café Timor is the premier coffee destination in Dili, serving the finest Timor-Leste coffee beans since 2010.',NULL,'["coffee","cafe","wifi","meeting place"]',NULL,156,42,4.5,28,1250,'pro',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1776906423,1776906423,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-2','Hotel Timor','hotel-timor','user-2','cat-2','business','live',NULL,NULL,'Maria Reis','77005678','+670',NULL,'reservations@hoteltimor.tl','Beach Road, Dili',-8.4833,125.5856,'{"monday":{"open":"00:00","close":"00:00"},"tuesday":{"open":"00:00","close":"00:00"}}','Hotel Timor offers luxury accommodation with stunning ocean views.',NULL,'["hotel","luxury","pool","wifi","restaurant"]',NULL,289,78,4.8,52,3420,'max',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1776906423,1776906423,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-3','Timor Tech Solutions','timor-tech-solutions','user-3','cat-6','business','live',NULL,NULL,'Carlos Almeida','77009999','+670',NULL,'carlos@timortech.tl','Building Trade, Dili',-8.5569,125.5603,'{"monday":{"open":"08:00","close":"17:00"},"tuesday":{"open":"08:00","close":"17:00"}}','Timor Tech Solutions provides IT consulting and web development services.',NULL,'["it","consulting","web development","software"]',NULL,87,23,4.2,15,890,'basic',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1776906423,1776906423,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-4','Beach Shop Dili','beach-shop-dili','user-1','cat-3','business','live',NULL,NULL,'Ana Costa','77004567','+670',NULL,'shop@beachdili.tl','Coastal Road, Dili',-8.4567,125.5734,NULL,'Beach Shop offers souvenirs, swimwear, and beach essentials.',NULL,'["souvenirs","swimwear","beach","shopping"]',NULL,45,12,4,8,456,'basic',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1776906423,1776906423,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-5','Timor Dental Clinic','timor-dental-clinic','user-2','cat-4','business','live',NULL,NULL,'Dr. Pedro Santos','77007890','+670',NULL,'info@timordental.tl','Main Street, Dili',-8.5569,125.5603,NULL,'Professional dental services with modern equipment.',NULL,'["dental","health","medical","clinic"]',NULL,67,18,4.6,22,789,'pro',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1776906423,1776906423,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-1777694938343','test business Name','test-business-name','qxPYNRXCn11ubNuTHFXJc4r9MMZg4ik2',NULL,'business','draft',NULL,NULL,'Nick','+670 123414','+670',NULL,'feaffa@gmail.com','fafafafaf',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1777694938,1777694938,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('gov-test-001','Ministry of Finance','ministry-finance','system',NULL,'nonprofit','live',NULL,NULL,NULL,NULL,'+670',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'2026-05-05 07:46:55',1777967215,'government','none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-002','Cafe Brisa Serena','cafe-brisa-serena','system',NULL,'business','live',NULL,NULL,NULL,'+670 7723 1234','+670',NULL,'hello@brisaserena.tl','Rua de Caminho, Dili',-8.5541,125.5735,NULL,'Waterfront cafe with sunset views',NULL,NULL,'food.cafes',445,0,4.5,203,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077423,1778077423,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-003','Timor Plaza','timor-plaza','system',NULL,'business','live',NULL,NULL,NULL,'+670 331 5678','+670',NULL,'info@timorplaza.tl','Avenida President Nicolas Lobato, Dili',-8.5578,125.5789,NULL,'Largest shopping center',NULL,NULL,'retail.shopping_malls',167,0,4,89,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077439,1778077439,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-004','Hosanna Supermarket','hosanna-supermarket','system',NULL,'business','live',NULL,NULL,NULL,'+670 331 9012','+670',NULL,'contact@hosanna.tl','Bidau Santana, Dili',-8.5389,125.5812,NULL,'Fresh produce since 2005',NULL,NULL,'retail.grocery',89,0,4.1,134,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077446,1778077446,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-005','Kokui Indonesian Restaurant','kokui-indonesian-restaurant','system',NULL,'business','live',NULL,NULL,NULL,'+670 7721 4567','+670',NULL,'reservasi@kokui.tl','Lacluta, Dili',-8.5512,125.5698,NULL,'Authentic Indonesian cuisine',NULL,NULL,'food.restaurants',234,0,4.3,178,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077451,1778077451,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-006','Lita Bakery and Cafe','lita-bakery-and-cafe','system',NULL,'business','live',NULL,NULL,NULL,'+670 331 3456','+670',NULL,'orders@litabakery.tl','Comoro, Dili',-8.5423,125.5545,NULL,'Fresh bread since 1998',NULL,NULL,'food.bakeries',567,0,4.4,212,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077457,1778077457,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-007','Ready M8 Auto Service','ready-m8-auto-service','system',NULL,'business','live',NULL,NULL,NULL,'+670 7723 7890','+670',NULL,'service@readym8.tl','Lelogu, Dili',-8.5489,125.5489,NULL,'Professional auto repair',NULL,NULL,'automotive.repair',345,0,4.6,98,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077464,1778077464,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('biz-008','Timor Language Center','timor-language-center','system',NULL,'business','live',NULL,NULL,NULL,'+670 331 7890','+670',NULL,'info@timorlc.tl','Farol, Dili',-8.5556,125.5612,NULL,'Language school - Tetum, Portuguese, English',NULL,NULL,'education.language',123,0,4.7,156,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077469,1778077469,NULL,'none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('ngo-001','CARE International Timor-Leste','care-international-timor-leste','system',NULL,'nonprofit','live',NULL,NULL,NULL,'+670 331 2100','+670',NULL,'info@careintl.tl','Fatumas Hel, Dili',-8.5523,125.5689,NULL,'Fighting poverty - gender equality, food security',NULL,NULL,'',234,0,4.8,67,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077474,1778077474,'ngo','none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('ngo-002','World Vision Timor-Leste','world-vision-timor-leste','system',NULL,'nonprofit','live',NULL,NULL,NULL,'+670 331 3456','+670',NULL,'info@wvi.org','Campo, Dili',-8.5498,125.5634,NULL,'Children well-being programs',NULL,NULL,'',189,0,4.7,89,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077479,1778077479,'ngo','none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('ngo-003','Plan International Timor-Leste','plan-international-timor-leste','system',NULL,'nonprofit','live',NULL,NULL,NULL,'+670 331 4567','+670',NULL,'info.tl@plan-international.org','Motael, Dili',-8.5567,125.5656,NULL,'Children rights and equality for girls',NULL,NULL,'',156,0,4.6,45,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077487,1778077487,'ngo','none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('ngo-004','Cruz Vermelha Timor-Leste','cruz-vermelha-timor-leste','system',NULL,'nonprofit','live',NULL,NULL,NULL,'+670 331 2345','+670',NULL,'cvtl@cvtimor.tl','Bairro Pite, Dili',-8.5512,125.5534,NULL,'Red Cross - humanitarian aid, disaster response',NULL,NULL,'',98,0,4.5,34,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077492,1778077492,'ngo','none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('gov-001','STAE - Electoral Administration','stae-electoral-administration','system',NULL,'nonprofit','live',NULL,NULL,NULL,'+670 331 1234','+670',NULL,'info@stae.tl','Palacio do Gov',-8.5534,125.5601,NULL,'Manages elections and democratic processes',NULL,NULL,'',67,0,4.2,23,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077497,1778077497,'government','none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('gov-002','Ministerio da Saude','ministerio-da-saude','system',NULL,'nonprofit','live',NULL,NULL,NULL,'+670 331 4567','+670',NULL,'geral@ms.gov.tl','Avenida do Museu, Dili',-8.5545,125.5589,NULL,'Public health policy and healthcare',NULL,NULL,'',134,0,4.4,56,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077505,1778077505,'government','none',NULL);
INSERT INTO "business_pages" ("id","title","slug","owner_id","category_id","entity_type","status","banner_image_id","profile_image_id","contact_name","contact_number","country_code","year_of_establishment","email","address","location_lat","location_lng","opening_hours","about_us","latest_updates","tags","industry","likes","saves","rating_average","rating_count","views","plan_type","publish_date","expiry_date","registration_url","verified_badge","social_links","photo_gallery","latest_update","latest_update_images","latest_update_date","created_at","updated_at","organization_type","subscription_status","grace_period_end_date") VALUES('gov-003','PMDTL - Protecao Civil','pmdtl-protecao-civil','system',NULL,'nonprofit','live',NULL,NULL,NULL,'+670 331 7890','+670',NULL,'protecao.civil@pmdtl.tl','Fatumeta, Dili',-8.5489,125.5567,NULL,'Civil protection and disaster management',NULL,NULL,'',45,0,4.3,19,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,1778077510,1778077510,'government','none',NULL);
