-- ============================================
-- Seed Data: Listing Categories (lc-*)
-- ============================================
INSERT OR IGNORE INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('lc-1', 'Jobs', 'jobs', 'Employment opportunities and job postings', '💼', NULL, 1, 1, '[{"name":"employmentType","type":"select","label":"Employment Type","required":true,"options":["Full-time","Part-time","Contract","Internship","Freelance"]},{"name":"salary","type":"number","label":"Salary"},{"name":"salaryCurrency","type":"select","label":"Currency","options":["USD","IDR","AUD","EUR"]},{"name":"salaryPeriod","type":"select","label":"Salary Period","options":["month","week","day","hour"]}]'),
('lc-2', 'For Sale', 'for-sale', 'Items for sale by individuals', '🏷️', NULL, 2, 1, '[{"name":"condition","type":"select","label":"Condition","required":true,"options":["New","Like New","Good","Fair","For Parts"]},{"name":"negotiable","type":"boolean","label":"Price Negotiable"}]'),
('lc-3', 'Vehicles', 'vehicles', 'Cars, motorcycles, and other vehicles', '🚗', NULL, 3, 1, '[{"name":"vehicleType","type":"select","label":"Vehicle Type","required":true,"options":["Car","Motorcycle","Bicycle","Boat","Truck","Van","Bus","Other"]},{"name":"make","type":"text","label":"Make/Brand","required":true},{"name":"model","type":"text","label":"Model","required":true},{"name":"year","type":"number","label":"Year"},{"name":"mileage","type":"number","label":"Mileage (km)"},{"name":"fuelType","type":"select","label":"Fuel Type","options":["Petrol","Diesel","Electric","Hybrid"]},{"name":"transmission","type":"select","label":"Transmission","options":["Manual","Automatic"]}]'),
('lc-4', 'Property', 'property', 'Real estate for sale', '🏠', NULL, 4, 1, '[{"name":"propertyType","type":"select","label":"Property Type","required":true,"options":["House","Apartment","Land","Commercial","Industrial"]},{"name":"bedrooms","type":"number","label":"Bedrooms"},{"name":"bathrooms","type":"number","label":"Bathrooms"},{"name":"landSize","type":"number","label":"Land Size (m²)"},{"name":"buildingSize","type":"number","label":"Building Size (m²)"}]'),
('lc-5', 'Rentals', 'rentals', 'Property and equipment for rent', '🔑', NULL, 5, 1, '[{"name":"rentalType","type":"select","label":"Rental Type","required":true,"options":["Apartment","House","Room","Office","Shop","Land","Equipment"]},{"name":"minRentalDays","type":"number","label":"Minimum Rental Days"},{"name":"availableFrom","type":"date","label":"Available From"},{"name":"furnished","type":"boolean","label":"Furnished"}]'),
('lc-6', 'Services', 'services', 'Professional and personal services', '🔧', NULL, 6, 1, '[{"name":"serviceType","type":"select","label":"Service Type","required":true,"options":["Professional","Repair","Cleaning","Beauty","Education","Events","Photography","Other"]},{"name":"serviceArea","type":"text","label":"Service Area"},{"name":"homeVisit","type":"boolean","label":"Home Visit Available"}]'),
('lc-7', 'Wanted', 'wanted', 'Items or services people are looking for', '🔍', NULL, 7, 1, '[{"name":"wantedType","type":"select","label":"Looking For","required":true,"options":["Item","Service","Property","Vehicle","Job","Other"]},{"name":"budget","type":"number","label":"Budget"}]'),
('lc-8', 'Events', 'events', 'Concerts, workshops, and community events', '🎭', NULL, 8, 1, '[{"name":"eventType","type":"select","label":"Event Type","required":true,"options":["Concert","Workshop","Conference","Festival","Sports","Community","Other"]},{"name":"eventDate","type":"date","label":"Event Date"},{"name":"ticketPrice","type":"number","label":"Ticket Price"},{"name":"freeEntry","type":"boolean","label":"Free Entry"}]'),
('lc-9', 'Pets', 'pets', 'Pets for sale, adoption, or looking for home', '🐾', NULL, 9, 1, '[{"name":"petType","type":"select","label":"Pet Type","required":true,"options":["Dog","Cat","Bird","Fish","Rabbit","Other"]},{"name":"breed","type":"text","label":"Breed"},{"name":"age","type":"select","label":"Age","options":["Baby","Young","Adult","Senior"]},{"name":"vaccinated","type":"boolean","label":"Vaccinated"}]'),
('lc-10', 'Agriculture', 'agriculture', 'Farm products, livestock, and agricultural equipment', '🌾', NULL, 10, 1, '[{"name":"agriType","type":"select","label":"Type","required":true,"options":["Crop","Livestock","Equipment","Seeds","Fertilizer","Other"]},{"name":"organic","type":"boolean","label":"Organic"}]');

-- Sub-categories
INSERT OR IGNORE INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('lc-2-1', 'Electronics', 'electronics', 'Phones, computers, and gadgets', '📱', 'lc-2', 21, 1, '[{"name":"brand","type":"text","label":"Brand","required":true},{"name":"model","type":"text","label":"Model"},{"name":"condition","type":"select","label":"Condition","required":true,"options":["New","Like New","Good","Fair","For Parts"]}]'),
('lc-2-2', 'Fashion', 'fashion', 'Clothing, shoes, and accessories', '👗', 'lc-2', 22, 1, '[{"name":"gender","type":"select","label":"Gender","options":["Men","Women","Unisex","Kids"]},{"name":"size","type":"text","label":"Size"},{"name":"condition","type":"select","label":"Condition","required":true,"options":["New","Like New","Good","Fair"]}]'),
('lc-2-3', 'Furniture', 'furniture', 'Home and office furniture', '🪑', 'lc-2', 23, 1, '[{"name":"furnitureType","type":"select","label":"Type","options":["Sofa","Bed","Table","Chair","Cabinet","Desk","Other"]},{"name":"material","type":"text","label":"Material"},{"name":"dimensions","type":"text","label":"Dimensions"}]');

-- ============================================
-- Seed Data: Business Categories (bc-*)
-- ============================================
INSERT OR IGNORE INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('bc-1', 'Restaurants & Cafés', 'restaurants-cafes', 'Food service establishments', '🍽️', NULL, 1, 1, '[{"name":"cuisineType","type":"select","label":"Cuisine Type","required":true,"options":["Timorese","Portuguese","Indonesian","Chinese","Indian","Italian","Fast Food","Seafood","Western","Fusion","Other"]},{"name":"priceRange","type":"select","label":"Price Range","options":["$","$$","$$$","$$$$"]},{"name":"openingHours","type":"text","label":"Opening Hours"},{"name":"outdoorSeating","type":"boolean","label":"Outdoor Seating"},{"name":"wifiAvailable","type":"boolean","label":"WiFi Available"}]'),
('bc-2', 'Accommodation', 'accommodation', 'Hotels, guesthouses, and lodging', '🏨', NULL, 2, 1, '[{"name":"accommodationType","type":"select","label":"Type","required":true,"options":["Hotel","Guesthouse","Homestay","Hostel","Resort","Villa","Lodge","Apartment"]},{"name":"starRating","type":"select","label":"Star Rating","options":["1 Star","2 Stars","3 Stars","4 Stars","5 Stars","Unrated"]},{"name":"roomCount","type":"number","label":"Number of Rooms"},{"name":"breakfastIncluded","type":"boolean","label":"Breakfast Included"},{"name":"poolAvailable","type":"boolean","label":"Pool Available"}]'),
('bc-3', 'Retail & Shops', 'retail-shops', 'Retail stores and shops', '🏪', NULL, 3, 1, '[{"name":"retailType","type":"select","label":"Store Type","required":true,"options":["Grocery","Clothing","Electronics","Furniture","Hardware","Pharmacy","Books","Sports","Beauty","Jewelry","Souvenirs","Other"]},{"name":"parkingAvailable","type":"boolean","label":"Parking Available"}]'),
('bc-4', 'Transportation', 'transportation', 'Transport services and vehicle rental', '🚗', NULL, 4, 1, '[{"name":"transportType","type":"select","label":"Service Type","required":true,"options":["Taxi","Rent-a-Car","Motorcycle Rental","Bus","Boat/Ferry","Airport Transfer","Trucking","Logistics","Driving School"]},{"name":"fleetSize","type":"number","label":"Fleet Size"},{"name":"homePickup","type":"boolean","label":"Home Pickup Available"}]'),
('bc-5', 'Professional Services', 'professional-services', 'Legal, accounting, consulting', '💼', NULL, 5, 1, '[{"name":"serviceType","type":"select","label":"Service Type","required":true,"options":["Legal","Accounting","Consulting","IT Services","Marketing","Architecture","Engineering","Insurance","Real Estate","Other"]},{"name":"languages","type":"text","label":"Languages Spoken"}]'),
('bc-6', 'Health & Wellness', 'health-wellness', 'Healthcare and wellness services', '🏥', NULL, 6, 1, '[{"name":"healthType","type":"select","label":"Service Type","required":true,"options":["Hospital","Clinic","Pharmacy","Dental","Optical","Laboratory","Physiotherapy","Mental Health","Gym/Fitness","Spa","Beauty Salon","Barbershop"]},{"name":"emergencyService","type":"boolean","label":"24/7 Emergency"},{"name":"insuranceAccepted","type":"boolean","label":"Insurance Accepted"}]'),
('bc-7', 'Education & Training', 'education-training', 'Schools, courses, and training', '🎓', NULL, 7, 1, '[{"name":"educationType","type":"select","label":"Institution Type","required":true,"options":["University","School","Vocational Training","Language School","Driving School","Music School","Art School","Tutoring Center","Online Platform","Other"]},{"name":"accreditation","type":"text","label":"Accreditation"}]'),
('bc-8', 'Construction & Trades', 'construction-trades', 'Building and home services', '🏗️', NULL, 8, 1, '[{"name":"tradeType","type":"select","label":"Service Type","required":true,"options":["General Contractor","Electrical","Plumbing","Painting","Carpentry","Roofing","Landscaping","Cleaning","Pest Control","AC Repair","Security Systems","Masonry","Other"]},{"name":"licensed","type":"boolean","label":"Licensed & Insured"},{"name":"freeQuote","type":"boolean","label":"Free Estimates"}]'),
('bc-9', 'Entertainment & Events', 'entertainment-events', 'Entertainment and event services', '🎭', NULL, 9, 1, '[{"name":"entertainmentType","type":"select","label":"Service Type","required":true,"options":["Cinema","Theater","Nightclub","Bar","Karaoke","Bowling","Arcade","Events Venue","Photography","Videography","DJ Services","Event Planning","Catering","Other"]},{"name":"capacity","type":"number","label":"Capacity (people)"}]'),
('bc-10', 'Agriculture & Farming', 'agriculture-farming', 'Agricultural products and services', '🌾', NULL, 10, 1, '[{"name":"agriType","type":"select","label":"Type","required":true,"options":["Farm","Nursery","AgriSupplier","Livestock","Fishery","Coffee Farm","Organic Farm","AgriProcessing","Other"]},{"name":"organicCertified","type":"boolean","label":"Organic Certified"}]'),
('bc-11', 'Computers & Electronics', 'computers-electronics', 'Tech shops and services', '💻', NULL, 11, 1, '[{"name":"techType","type":"select","label":"Service Type","required":true,"options":["Computer Shop","Phone Shop","Repair Service","Software Development","Web Design","IT Support","Network Installation","CCTV Installation","Gaming","Other"]},{"name":"warrantyOffered","type":"boolean","label":"Warranty Offered"}]'),
('bc-12', 'Fashion & Beauty', 'fashion-beauty', 'Clothing, accessories, and beauty services', '👗', NULL, 12, 1, '[{"name":"fashionType","type":"select","label":"Business Type","required":true,"options":["Clothing Store","Shoes","Accessories","Tailoring","Laundry/Dry Clean","Hair Salon","Nail Salon","Barbershop","Spa","Makeup Artist","Fashion Designer","Other"]},{"name":"customOrders","type":"boolean","label":"Custom Orders"}]');

-- ============================================
-- Seed Data: Non-Profit Categories (npc-*)
-- ============================================
INSERT OR IGNORE INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('npc-1', 'Humanitarian Aid', 'humanitarian-aid', 'Emergency relief and humanitarian organizations', '❤️', NULL, 1, 1, '[{"name":"focusArea","type":"select","label":"Focus Area","required":true,"options":["Emergency Response","Food Security","Shelter","Health","Education","Water & Sanitation","Protection","Multiple"]},{"name":"responseCapacity","type":"select","label":"Response Capacity","options":["Local","Regional","National","International"]}]'),
('npc-2', 'Education', 'education-ngo', 'Educational organizations and programs', '📚', NULL, 2, 1, '[{"name":"educationType","type":"select","label":"Type","required":true,"options":["Formal Education","Non-Formal Education","Vocational Training","Teacher Training","Scholarship Programs","Literacy Programs","Early Childhood","Multiple"]},{"name":"freeOrSubsidized","type":"boolean","label":"Free or Subsidized"}]'),
('npc-3', 'Healthcare', 'healthcare-ngo', 'Health and medical organizations', '🏥', NULL, 3, 1, '[{"name":"healthType","type":"select","label":"Type","required":true,"options":["Hospital","Clinic","Mobile Clinic","Community Health","Mental Health","Maternal Health","HIV/AIDS","Malaria","Tuberculosis","Vaccination","Nutrition","Multiple"]},{"name":"freeService","type":"boolean","label":"Free Services"}]'),
('npc-4', 'Environment', 'environment', 'Environmental protection and conservation', '🌍', NULL, 4, 1, '[{"name":"environmentType","type":"select","label":"Focus","required":true,"options":["Conservation","Reforestation","Marine Protection","Wildlife","Climate Change","Waste Management","Water Conservation","Sustainable Energy","Environmental Education","Multiple"]}]'),
('npc-5', 'Women & Children', 'women-children', 'Organizations supporting women and children', '👶', NULL, 5, 1, '[{"name":"focusArea","type":"select","label":"Focus","required":true,"options":["Gender Equality","Violence Prevention","Womens Rights","Child Protection","Orphan Support","Youth Development","Early Childhood Development","Multiple"]}]'),
('npc-6', 'Youth Development', 'youth-development', 'Youth empowerment and development programs', '🌟', NULL, 6, 1, '[{"name":"programType","type":"select","label":"Program Type","required":true,"options":["Skills Training","Sports","Arts & Culture","Leadership","Entrepreneurship","Volunteer Programs","Mentorship","Civic Engagement","Multiple"]}]'),
('npc-7', 'Agriculture & Food Security', 'agriculture-food', 'Food security and agricultural development', '🌾', NULL, 7, 1, '[{"name":"agriType","type":"select","label":"Type","required":true,"options":["Food Security","Sustainable Agriculture","Livestock","Fishing","Nutrition","Food Distribution","Agricultural Training","Seed Distribution","Multiple"]}]'),
('npc-8', 'Governance & Advocacy', 'governance-advocacy', 'Civic engagement and policy advocacy', '⚖️', NULL, 8, 1, '[{"name":"focusArea","type":"select","label":"Focus","required":true,"options":["Human Rights","Democracy","Transparency","Anti-Corruption","Civic Education","Justice","Good Governance","Research & Advocacy","Multiple"]}]'),
('npc-9', 'Disability Inclusion', 'disability-inclusion', 'Organizations supporting people with disabilities', '♿', NULL, 9, 1, '[{"name":"focusArea","type":"select","label":"Focus","required":true,"options":["Physical Disability","Visual Impairment","Hearing Impairment","Intellectual Disability","Multiple Disabilities","Inclusion Advocacy","Assistive Technology","Rehabilitation","Multiple"]}]'),
('npc-10', 'Emergency & Disaster', 'emergency-disaster', 'Disaster preparedness and response', '🚨', NULL, 10, 1, '[{"name":"preparednessType","type":"select","label":"Type","required":true,"options":["Disaster Response","Disaster Preparedness","Search & Rescue","First Aid","Emergency Shelter","Early Warning Systems","Climate Adaptation","Multiple"]}]'),
('npc-11', 'Community Development', 'community-development', 'Local community development organizations', '🏘️', NULL, 11, 1, '[{"name":"focusArea","type":"select","label":"Focus","required":true,"options":["Infrastructure","Water & Sanitation","Energy Access","Income Generation","Local Governance","Social Cohesion","Cultural Preservation","Multiple"]}]'),
('npc-12', 'Arts & Culture', 'arts-culture', 'Arts, culture, and heritage organizations', '🎨', NULL, 12, 1, '[{"name":"cultureType","type":"select","label":"Type","required":true,"options":["Traditional Arts","Performing Arts","Visual Arts","Music","Film & Media","Heritage Preservation","Cultural Education","Crafts & Textiles","Multiple"]}]');

-- ============================================
-- Seed Data: Public Sector Categories (psc-*)
-- ============================================
INSERT OR IGNORE INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('psc-1', 'National Government', 'national-government', 'National ministries and government agencies', '🏛️', NULL, 1, 1, '[{"name":"ministryName","type":"text","label":"Ministry Name","required":true},{"name":"headquarters","type":"text","label":"Headquarters Location"},{"name":"regionalOffices","type":"number","label":"Number of Regional Offices"}]'),
('psc-2', 'Municipal & District', 'municipal-district', 'Local government offices', '🏢', NULL, 2, 1, '[{"name":"adminLevel","type":"select","label":"Admin Level","required":true,"options":["Municipality","Administrative Post","Suco/Suburb","Aldeia"]},{"name":"population","type":"number","label":"Population Served"}]'),
('psc-3', 'Justice & Law', 'justice-law', 'Courts, police, and legal services', '⚖️', NULL, 3, 1, '[{"name":"justiceType","type":"select","label":"Type","required":true,"options":["Court","Prosecutor Office","Public Defender","Police Station","Prison","Legal Aid","Alternative Dispute Resolution"]},{"name":"jurisdiction","type":"text","label":"Jurisdiction Area"}]'),
('psc-4', 'Education', 'education-public', 'Public schools and educational institutions', '🏫', NULL, 4, 1, '[{"name":"schoolType","type":"select","label":"Type","required":true,"options":["Primary School","Secondary School","Technical School","University","Vocational Training Center","Teacher Training"]},{"name":"studentCount","type":"number","label":"Number of Students"}]'),
('psc-5', 'Healthcare', 'healthcare-public', 'Public hospitals and health centers', '🏥', NULL, 5, 1, '[{"name":"healthType","type":"select","label":"Type","required":true,"options":["National Hospital","Referral Hospital","Municipal Health Center","Community Health Center","Health Post","Maternal & Child Health","Laboratory","Pharmacy"]},{"name":"bedsAvailable","type":"number","label":"Number of Beds"},{"name":"emergencyService","type":"boolean","label":"24/7 Emergency"}]'),
('psc-6', 'Agriculture & Rural', 'agriculture-rural', 'Agricultural extension and rural development', '🌾', NULL, 6, 1, '[{"name":"agriServiceType","type":"select","label":"Type","required":true,"options":["Agriculture Extension","Livestock","Fisheries","Forestry","Cooperatives","Rural Development","Irrigation","Agricultural Research"]}]'),
('psc-7', 'Infrastructure & Utilities', 'infrastructure-utilities', 'Public works, transport, and utilities', '🔧', NULL, 7, 1, '[{"name":"infraType","type":"select","label":"Type","required":true,"options":["Roads & Bridges","Water Supply","Electricity","Telecommunications","Port Authority","Airport","Public Transport","Waste Management"]}]'),
('psc-8', 'Social Services', 'social-services', 'Social welfare and protection services', '🤝', NULL, 8, 1, '[{"name":"socialType","type":"select","label":"Type","required":true,"options":["Social Security","Pensions","Disability Benefits","Child Protection","Elderly Care","Food Assistance","Housing Support","Veteran Services","Refugee Services"]}]'),
('psc-9', 'Tax & Finance', 'tax-finance', 'Tax offices and financial services', '💰', NULL, 9, 1, '[{"name":"financeType","type":"select","label":"Type","required":true,"options":["Tax Office","Customs","Treasury","National Bank","Revenue Authority","Customs Authority"]}]'),
('psc-10', 'Immigration & Consular', 'immigration-consular', 'Passports, visas, and consular services', '🛂', NULL, 10, 1, '[{"name":"serviceType","type":"select","label":"Type","required":true,"options":["Passport Office","Visa Services","Emigration","Consular Affairs","Foreign Embassy","Immigration Control"]}]'),
('psc-11', 'Environment & Land', 'environment-land', 'Environmental protection and land administration', '🌳', NULL, 11, 1, '[{"name":"envType","type":"select","label":"Type","required":true,"options":["Environmental Agency","Land Registry","Cadastral Office","Spatial Planning","Geology & Mines","Water Resources","Meteorology"]}]'),
('psc-12', 'Employment & Labor', 'employment-labor', 'Employment services and labor offices', '👷', NULL, 12, 1, '[{"name":"laborType","type":"select","label":"Type","required":true,"options":["Labor Office","Employment Agency","Vocational Training","Social Security Institute","Workers Union","Occupational Safety"]}]');

-- ============================================
-- Seed Data: Blog Categories (blc-*)
-- ============================================
INSERT OR IGNORE INTO blog_categories (id, name, slug, description, icon, sort_order, is_active) VALUES
('blc-1', 'News', 'news', 'Latest news and updates', '📰', 1, 1),
('blc-2', 'Business', 'business', 'Business tips and success stories', '💼', 2, 1),
('blc-3', 'Travel', 'travel', 'Travel guides and recommendations', '✈️', 3, 1),
('blc-4', 'Culture', 'culture', 'Timorese culture and traditions', '🎭', 4, 1),
('blc-5', 'Food', 'food', 'Food and recipes', '🍽️', 5, 1),
('blc-6', 'Events', 'events', 'Upcoming events and activities', '📅', 6, 1),
('blc-7', 'Community', 'community', 'Community stories and initiatives', '👥', 7, 1),
('blc-8', 'Tips', 'tips', 'Helpful tips and guides', '💡', 8, 1);