// Test Utilities - Data Factories
// Generated by BMAD TEA

import { test as base, type Page, type Locator } from '@playwright/test';

// ============================================
// User Factory
// ============================================

export interface TestUser {
  id: string;
  email: string;
  name: string;
  phone?: string;
  role: 'user' | 'admin';
  isVerified: boolean;
  createdAt: Date;
}

let userIdCounter = 1;

export const UserFactory = {
  /**
   * Create a new user data object
   */
  build(overrides: Partial<TestUser> = {}): TestUser {
    const id = `user_${userIdCounter++}_${Date.now()}`;
    return {
      id,
      email: overrides.email || `testuser${Date.now()}@example.com`,
      name: overrides.name || 'Test User',
      phone: overrides.phone || '+67077234567',
      role: overrides.role || 'user',
      isVerified: overrides.isVerified ?? false,
      createdAt: new Date(),
      ...overrides,
    };
  },

  /**
   * Create and register a user via UI
   */
  async createViaUI(page: Page, userData?: Partial<TestUser>): Promise<TestUser> {
    const user = this.build(userData);
    
    await page.goto('/register');
    await page.fill('input[name="name"]', user.name);
    await page.fill('input[name="email"]', user.email);
    await page.fill('input[name="password"]', 'TestPassword123!');
    await page.fill('input[name="confirmPassword"]', 'TestPassword123!');
    await page.click('button[type="submit"]');
    
    // Wait for registration to complete
    await page.waitForURL(/\/(dashboard|login)/, { timeout: 10000 });
    
    return user;
  },

  /**
   * Create user via API (if available)
   */
  async createViaAPI(page: Page, userData?: Partial<TestUser>): Promise<TestUser> {
    const user = this.build(userData);
    
    const response = await page.request.post('/api/auth/register', {
      data: {
        email: user.email,
        password: 'TestPassword123!',
        name: user.name,
      },
    });
    
    if (!response.ok()) {
      throw new Error(`Failed to create user: ${response.status()}`);
    }
    
    return user;
  },
};

// ============================================
// Business Factory
// ============================================

export interface TestBusiness {
  id: string;
  name: string;
  slug: string;
  description?: string;
  category: string;
  subcategory?: string;
  status: 'draft' | 'pending' | 'published' | 'expired' | 'unpaid';
  ownerId: string;
  contactName: string;
  phone: string;
  email: string;
  address: string;
  latitude?: number;
  longitude?: number;
  openingHours?: Record<string, { open?: string; close?: string; closed?: boolean }>;
  tags: string[];
  likes: number;
  views: number;
}

let businessIdCounter = 1;

export const BusinessFactory = {
  /**
   * Create a new business data object
   */
  build(ownerId: string, overrides: Partial<TestBusiness> = {}): TestBusiness {
    const id = `biz_${businessIdCounter++}_${Date.now()}`;
    return {
      id,
      name: overrides.name || `Test Business ${id}`,
      slug: overrides.slug || `test-business-${id}`,
      description: overrides.description || 'Test business description',
      category: overrides.category || 'restaurant',
      subcategory: overrides.subcategory || 'cafe',
      status: overrides.status || 'draft',
      ownerId,
      contactName: overrides.contactName || 'Test Contact',
      phone: overrides.phone || '+67077234567',
      email: overrides.email || 'test@business.com',
      address: overrides.address || 'Dili, Timor-Leste',
      latitude: overrides.latitude || -8.5569,
      longitude: overrides.longitude || 125.5603,
      openingHours: overrides.openingHours || {
        monday: { open: '09:00', close: '18:00' },
        tuesday: { open: '09:00', close: '18:00' },
        wednesday: { open: '09:00', close: '18:00' },
        thursday: { open: '09:00', close: '18:00' },
        friday: { open: '09:00', close: '18:00' },
        saturday: { open: '10:00', close: '14:00', closed: false },
        sunday: { closed: true },
      },
      tags: overrides.tags || ['test', 'restaurant', 'dili'],
      likes: overrides.likes || 0,
      views: overrides.views || 0,
      ...overrides,
    };
  },

  /**
   * Create business via UI
   */
  async createViaUI(page: Page, ownerId: string, businessData?: Partial<TestBusiness>): Promise<TestBusiness> {
    const business = this.build(ownerId, businessData);
    
    // Navigate to create business page
    await page.goto('/dashboard/business/new');
    
    // Fill in business details
    await page.fill('input[name="name"]', business.name);
    await page.selectOption('select[name="category"]', business.category);
    await page.fill('input[name="contactName"]', business.contactName);
    await page.fill('input[name="phone"]', business.phone);
    await page.fill('input[name="email"]', business.email);
    await page.fill('textarea[name="address"]', business.address);
    
    // Submit form
    await page.click('button[type="submit"]');
    
    // Wait for creation
    await page.waitForURL(/\/dashboard\/business/);
    
    return business;
  },
};

// ============================================
// Product Factory
// ============================================

export interface TestProduct {
  id: string;
  businessId: string;
  name: string;
  description?: string;
  price?: number;
  images: string[];
  isActive: boolean;
}

let productIdCounter = 1;

export const ProductFactory = {
  /**
   * Create a new product data object
   */
  build(businessId: string, overrides: Partial<TestProduct> = {}): TestProduct {
    const id = `prod_${productIdCounter++}_${Date.now()}`;
    return {
      id,
      businessId,
      name: overrides.name || `Test Product ${id}`,
      description: overrides.description || 'Test product description',
      price: overrides.price || 10.00,
      images: overrides.images || [],
      isActive: overrides.isActive ?? true,
      ...overrides,
    };
  },
};

// ============================================
// Review Factory
// ============================================

export interface TestReview {
  id: string;
  businessId: string;
  userId: string;
  rating: number;
  comment?: string;
  createdAt: Date;
}

let reviewIdCounter = 1;

export const ReviewFactory = {
  /**
   * Create a new review data object
   */
  build(businessId: string, userId: string, overrides: Partial<TestReview> = {}): TestReview {
    const id = `review_${reviewIdCounter++}_${Date.now()}`;
    return {
      id,
      businessId,
      userId,
      rating: overrides.rating || Math.floor(Math.random() * 5) + 1,
      comment: overrides.comment || 'Great place!',
      createdAt: new Date(),
      ...overrides,
    };
  },
};

// ============================================
// Custom Test Fixture
// ============================================

export interface TestFixtures {
  testUser: TestUser;
  testBusiness: TestBusiness;
  testProduct: TestProduct;
  testReview: TestReview;
}

export const test = base.extend<TestFixtures>({
  // This allows tests to access the factories
  testUser: async ({ page }, use) => {
    await use(UserFactory.build());
  },
  testBusiness: async ({ page }, use) => {
    const user = UserFactory.build();
    await use(BusinessFactory.build(user.id));
  },
  testProduct: async ({ page }, use) => {
    const user = UserFactory.build();
    const business = BusinessFactory.build(user.id);
    await use(ProductFactory.build(business.id));
  },
  testReview: async ({ page }, use) => {
    const user = UserFactory.build();
    const business = BusinessFactory.build(user.id);
    await use(ReviewFactory.build(business.id, user.id));
  },
});

// ============================================
// Helper Functions
// ============================================

/**
 * Clean up test data after tests
 */
export async function cleanupTestData(page: Page) {
  // Clear cookies - safely ignore localStorage errors
  await page.context().clearCookies();
  try {
    // Only clear localStorage if the page allows it (not about:blank or cross-origin)
    const url = page.url();
    if (url && !url.startsWith('about:') && url.startsWith('http')) {
      await page.evaluate(() => localStorage.clear());
    }
  } catch {
    // Ignore localStorage errors - page might be restricted
  }
}

/**
 * Login as test user
 */
export async function loginAsUser(page: Page, email?: string, password?: string) {
  await page.goto('/login');
  await page.fill('input[name="email"]', email || 'test@example.com');
  await page.fill('input[name="password"]', password || 'TestPassword123!');
  await page.click('button[type="submit"]');
  await page.waitForURL('/dashboard');
}

/**
 * Login as admin
 */
export async function loginAsAdmin(page: Page) {
  await page.goto('/admin/login');
  await page.fill('input[name="email"]', 'admin@example.com');
  await page.fill('input[name="password"]', 'admin123');
  await page.click('button[type="submit"]');
  
  // Wait for navigation to complete (the page will redirect to /admin on success)
  try {
    await page.waitForURL('**/admin**', { timeout: 5000 });
  } catch (e) {
    // If redirect doesn't happen, check if there's an error message
    const errorMsg = await page.locator('#error-message').textContent();
    if (errorMsg && !errorMsg.includes('hidden')) {
      throw new Error(`Login failed: ${errorMsg}`);
    }
  }
  
  // Wait a bit for cookies to be set
  await page.waitForTimeout(500);
}

export { expect } from '@playwright/test';
