/**
 * Standardized error codes for TimorUp
 */
export enum ErrorCode {
  // Auth errors (1xxx)
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_INVALID = 'AUTH_INVALID',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_RATE_LIMITED = 'AUTH_RATE_LIMITED',
  AUTH_USER_EXISTS = 'AUTH_USER_EXISTS',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',

  // Business errors (2xxx)
  BUSINESS_NOT_FOUND = 'BUSINESS_NOT_FOUND',
  BUSINESS_LIMIT_REACHED = 'BUSINESS_LIMIT_REACHED',
  BUSINESS_FORBIDDEN = 'BUSINESS_FORBIDDEN',
  BUSINESS_SLUG_EXISTS = 'BUSINESS_SLUG_EXISTS',

  // Product/SKU errors (3xxx)
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_NOT_ALLOWED = 'PRODUCT_SKU_NOT_ALLOWED',
  PRODUCT_LIMIT_REACHED = 'PRODUCT_LIMIT_REACHED',

  // Validation errors (4xxx)
  VALIDATION_INVALID_INPUT = 'VALIDATION_INVALID_INPUT',
  VALIDATION_JSON_ERROR = 'VALIDATION_JSON_ERROR',
  VALIDATION_EMAIL_INVALID = 'VALIDATION_EMAIL_INVALID',
  VALIDATION_PHONE_INVALID = 'VALIDATION_PHONE_INVALID',
  VALIDATION_PASSWORD_TOO_WEAK = 'VALIDATION_PASSWORD_TOO_WEAK',

  // Subscription errors (5xxx)
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_NONE = 'SUBSCRIPTION_NONE',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_GRACE_PERIOD = 'SUBSCRIPTION_GRACE_PERIOD',

  // Media errors (6xxx)
  MEDIA_NO_FILE = 'MEDIA_NO_FILE',
  MEDIA_TYPE_NOT_ALLOWED = 'MEDIA_TYPE_NOT_ALLOWED',
  MEDIA_SIZE_TOO_LARGE = 'MEDIA_SIZE_TOO_LARGE',
  MEDIA_LIMIT_REACHED = 'MEDIA_LIMIT_REACHED',
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  MEDIA_UPLOAD_ERROR = 'MEDIA_UPLOAD_ERROR',
  MEDIA_FORMAT_INVALID = 'MEDIA_FORMAT_INVALID',

  // Server errors (9xxx)
  SERVER_ERROR = 'SERVER_ERROR',
  SERVER_DB_ERROR = 'SERVER_DB_ERROR',
  SERVER_TIMEOUT = 'SERVER_TIMEOUT',
  SERVER_NOT_IMPLEMENTED = 'SERVER_NOT_IMPLEMENTED',
}

// HTTP status codes mapped to error codes
export const ErrorCodeToStatus: Record<ErrorCode, number> = {
  [ErrorCode.AUTH_REQUIRED]: 401,
  [ErrorCode.AUTH_INVALID]: 401,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_RATE_LIMITED]: 429,
  [ErrorCode.AUTH_USER_EXISTS]: 409,
  [ErrorCode.AUTH_SESSION_EXPIRED]: 401,

  [ErrorCode.BUSINESS_NOT_FOUND]: 404,
  [ErrorCode.BUSINESS_LIMIT_REACHED]: 403,
  [ErrorCode.BUSINESS_FORBIDDEN]: 403,
  [ErrorCode.BUSINESS_SLUG_EXISTS]: 409,

  [ErrorCode.PRODUCT_NOT_FOUND]: 404,
  [ErrorCode.PRODUCT_SKU_NOT_ALLOWED]: 403,
  [ErrorCode.PRODUCT_LIMIT_REACHED]: 403,

  [ErrorCode.VALIDATION_INVALID_INPUT]: 400,
  [ErrorCode.VALIDATION_JSON_ERROR]: 400,
  [ErrorCode.VALIDATION_EMAIL_INVALID]: 400,
  [ErrorCode.VALIDATION_PHONE_INVALID]: 400,
  [ErrorCode.VALIDATION_PASSWORD_TOO_WEAK]: 400,

  [ErrorCode.SUBSCRIPTION_EXPIRED]: 403,
  [ErrorCode.SUBSCRIPTION_NONE]: 403,
  [ErrorCode.SUBSCRIPTION_CANCELLED]: 403,
  [ErrorCode.SUBSCRIPTION_GRACE_PERIOD]: 403,

  [ErrorCode.MEDIA_NO_FILE]: 400,
  [ErrorCode.MEDIA_TYPE_NOT_ALLOWED]: 400,
  [ErrorCode.MEDIA_SIZE_TOO_LARGE]: 400,
  [ErrorCode.MEDIA_LIMIT_REACHED]: 403,
  [ErrorCode.MEDIA_NOT_FOUND]: 404,
  [ErrorCode.MEDIA_UPLOAD_ERROR]: 500,
  [ErrorCode.MEDIA_FORMAT_INVALID]: 400,

  [ErrorCode.SERVER_ERROR]: 500,
  [ErrorCode.SERVER_DB_ERROR]: 500,
  [ErrorCode.SERVER_TIMEOUT]: 504,
  [ErrorCode.SERVER_NOT_IMPLEMENTED]: 501,
};