/**
 * Businesses Seed Data
 * TimorUp (2026-05-21)
 *
 * 18 businesses with realistic Timor-Leste data
 * Each business has 2-3 products/services
 */

const now = Math.floor(Date.now() / 1000);

export const businesses = [
  // Food & Dining
  {
    id: "biz-cafe-timor",
    title: "Café Timor",
    slug: "cafe-timor",
    description: "Premier coffee destination serving finest Timor-Leste coffee beans",
    ownerId: "owner-1",
    categoryId: "cafes",
    status: "published",
    contactName: "João Silva",
    contactNumber: "77001234",
    countryCode: "+670",
    email: "info@cafetimor.tl",
    address: "Avenida de Portugal, Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "Mon-Fri: 7AM-10PM, Sat-Sun: 8AM-11PM",
    aboutUs: "Café Timor serves the finest Timor-Leste coffee since 2010. Cozy atmosphere for meetings, study sessions, or relaxing with friends.",
    tags: "coffee,cafe,wifi,meeting place",
    likes: 156,
    saves: 42,
    views: 1250,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ instagram: "@cafetimor", facebook: "cafetimortl" }),
    createdAt: now - 86400 * 180,
    updatedAt: now - 86400 * 5,
  },
  {
    id: "biz-warung-nazar",
    title: "Warung Nazar",
    slug: "warung-nazar",
    description: "Authentic Timorese cuisine and local dishes",
    ownerId: "owner-2",
    categoryId: "restaurants",
    status: "published",
    contactName: "Nazar Santos",
    contactNumber: "77002345",
    countryCode: "+670",
    email: "nazarwarung@gmail.com",
    address: "Comoro Road, Dili",
    locationLat: -8.5456,
    locationLng: 125.5578,
    openingHours: "Daily: 6AM-9PM",
    aboutUs: "Traditional Timorese home-style cooking. Fresh local ingredients daily.",
    tags: "timorese,local food,home cooking",
    likes: 89,
    saves: 23,
    views: 678,
    verifiedBadge: 0,
    socialLinks: JSON.stringify({}),
    createdAt: now - 86400 * 90,
    updatedAt: now - 86400 * 10,
  },
  {
    id: "biz-burger-king-dili",
    title: "Burger King Timor",
    slug: "burger-king-dili",
    description: "International fast food chain in Dili",
    ownerId: "owner-3",
    categoryId: "fast-food",
    status: "published",
    contactName: "Maria Belo",
    contactNumber: "77003456",
    countryCode: "+670",
    email: "dili@burgerking.tl",
    address: "Beach Road, Dili",
    locationLat: -8.4833,
    locationLng: 125.5856,
    openingHours: "Daily: 10AM-10PM",
    aboutUs: "International fast food chain offering quality burgers and meals.",
    tags: "fast food,burger,international",
    likes: 234,
    saves: 56,
    views: 2340,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ instagram: "@bkdili" }),
    createdAt: now - 86400 * 365,
    updatedAt: now - 86400 * 30,
  },

  // Accommodation
  {
    id: "biz-hotel-timor",
    title: "Hotel Timor",
    slug: "hotel-timor",
    description: "Luxury oceanfront hotel on Beach Road",
    ownerId: "owner-4",
    categoryId: "hotels",
    status: "published",
    contactName: "Maria Reis",
    contactNumber: "77005678",
    countryCode: "+670",
    email: "reservations@hoteltimor.tl",
    address: "Beach Road, Dili",
    locationLat: -8.4833,
    locationLng: 125.5856,
    openingHours: "24/7",
    aboutUs: "Luxury accommodation with stunning ocean views. Swimming pool, restaurant, and conference facilities.",
    tags: "hotel,luxury,pool,ocean view",
    likes: 289,
    saves: 78,
    views: 3420,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ instagram: "@hoteltimorl", facebook: "HotelTimorTL" }),
    createdAt: now - 86400 * 730,
    updatedAt: now - 86400 * 7,
  },
  {
    id: "biz-guesthouse-santa",
    title: "Guesthouse Santa Cruz",
    slug: "guesthouse-santa-cruz",
    description: "Budget-friendly guesthouse near beach",
    ownerId: "owner-5",
    categoryId: "guesthouses",
    status: "published",
    contactName: "Francisco Soares",
    contactNumber: "77006789",
    countryCode: "+670",
    email: "santacruzgh@gmail.com",
    address: "Santa Cruz Beach, Dili",
    locationLat: -8.4678,
    locationLng: 125.5689,
    openingHours: "Check-in: 2PM, Check-out: 11AM",
    aboutUs: "Clean, affordable rooms steps from the beach. Perfect for budget travelers.",
    tags: "guesthouse,budget,beach,near airport",
    likes: 67,
    saves: 34,
    views: 890,
    verifiedBadge: 0,
    socialLinks: JSON.stringify({}),
    createdAt: now - 86400 * 200,
    updatedAt: now - 86400 * 15,
  },

  // Technology & IT
  {
    id: "biz-timor-tech",
    title: "Timor Tech Solutions",
    slug: "timor-tech-solutions",
    description: "Professional IT consulting and web development",
    ownerId: "owner-6",
    categoryId: "software",
    status: "published",
    contactName: "Carlos Almeida",
    contactNumber: "77009999",
    countryCode: "+670",
    email: "carlos@timortech.tl",
    address: "Trade Tower, Level 3, Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "Mon-Fri: 8AM-5PM",
    aboutUs: "IT consulting, web development, and tech support for businesses.",
    tags: "it,consulting,web development,tech support",
    likes: 87,
    saves: 23,
    views: 890,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ linkedin: "timor-tech" }),
    createdAt: now - 86400 * 400,
    updatedAt: now - 86400 * 3,
  },
  {
    id: "biz-phone-world",
    title: "Phone World Timor",
    slug: "phone-world-timor",
    description: "Mobile phones, accessories, and repair services",
    ownerId: "owner-7",
    categoryId: "phone-shops",
    status: "published",
    contactName: "Rui Fernandes",
    contactNumber: "77001234",
    countryCode: "+670",
    email: "phoneworld.tl@gmail.com",
    address: "Lacar Lecidere, Dili",
    locationLat: -8.5590,
    locationLng: 125.5620,
    openingHours: "Daily: 8AM-8PM",
    aboutUs: "Latest smartphones, SIM cards, top-ups, and professional repair services.",
    tags: "phones,accessories,repair,sim card",
    likes: 145,
    saves: 38,
    views: 1560,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ instagram: "@phoneworldtl" }),
    createdAt: now - 86400 * 500,
    updatedAt: now - 86400 * 1,
  },

  // Health & Wellness
  {
    id: "biz-dental-clinic",
    title: "Timor Dental Clinic",
    slug: "timor-dental-clinic",
    description: "Professional dental services with modern equipment",
    ownerId: "owner-8",
    categoryId: "dental",
    status: "published",
    contactName: "Dr. Pedro Santos",
    contactNumber: "77007890",
    countryCode: "+670",
    email: "info@timordental.tl",
    address: "Main Street, Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "Mon-Sat: 8AM-5PM",
    aboutUs: "Comprehensive dental care: check-ups, cleanings, fillings, and cosmetic dentistry.",
    tags: "dental,health,medical,clinic",
    likes: 67,
    saves: 18,
    views: 789,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({}),
    createdAt: now - 86400 * 300,
    updatedAt: now - 86400 * 20,
  },
  {
    id: "biz-pharma-plus",
    title: "Pharma Plus Dili",
    slug: "pharma-plus-dili",
    description: "Pharmacy with wide range of medicines and health products",
    ownerId: "owner-9",
    categoryId: "pharmacies",
    status: "published",
    contactName: "Ana Lima",
    contactNumber: "77004567",
    countryCode: "+670",
    email: "pharmaplus.tl@gmail.com",
    address: "Bidau Lecidere, Dili",
    locationLat: -8.5489,
    locationLng: 125.5645,
    openingHours: "Daily: 7AM-10PM",
    aboutUs: "Wide selection of medicines, health products, and cosmetics. Professional advice available.",
    tags: "pharmacy,medicine,health,cosmetics",
    likes: 98,
    saves: 27,
    views: 1120,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "PharmaPlusDili" }),
    createdAt: now - 86400 * 450,
    updatedAt: now - 86400 * 2,
  },
  {
    id: "biz-fit-gym",
    title: "Fitness First Timor",
    slug: "fitness-first-timor",
    description: "Modern gym with personal training services",
    ownerId: "owner-10",
    categoryId: "gyms",
    status: "published",
    contactName: "Paulo Gusmão",
    contactNumber: "77005678",
    countryCode: "+670",
    email: "info@fitnessfirst.tl",
    address: "Camboa, Dili",
    locationLat: -8.5345,
    locationLng: 125.5523,
    openingHours: "Daily: 5AM-10PM",
    aboutUs: "Modern equipment, personal trainers, and group classes. Yoga, Zumba, and weight training.",
    tags: "gym,fitness,personal training,yoga",
    likes: 134,
    saves: 45,
    views: 1670,
    verifiedBadge: 0,
    socialLinks: JSON.stringify({ instagram: "@fitnessfirsttl" }),
    createdAt: now - 86400 * 180,
    updatedAt: now - 86400 * 8,
  },

  // Education
  {
    id: "biz-english-center",
    title: "English Learning Center Timor",
    slug: "english-learning-center",
    description: "Professional English language courses",
    ownerId: "owner-11",
    categoryId: "language-centers",
    status: "published",
    contactName: "Susan Brown",
    contactNumber: "77009876",
    countryCode: "+670",
    email: "info@englishtimor.tl",
    address: "Fatuhada, Dili",
    locationLat: -8.5623,
    locationLng: 125.5698,
    openingHours: "Mon-Fri: 8AM-7PM, Sat: 9AM-1PM",
    aboutUs: "IELTS and TOEIC preparation, conversational English, business English courses.",
    tags: "english,language,ielts,education",
    likes: 78,
    saves: 32,
    views: 920,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "EnglishTimor" }),
    createdAt: now - 86400 * 365,
    updatedAt: now - 86400 * 12,
  },

  // Beauty & Personal Care
  {
    id: "biz-salon-maria",
    title: "Salon Maria",
    slug: "salon-maria",
    description: "Hair salon and beauty services",
    ownerId: "owner-12",
    categoryId: "salons",
    status: "published",
    contactName: "Maria Oliveira",
    contactNumber: "77002345",
    countryCode: "+670",
    email: "mariasalon.tl@gmail.com",
    address: "Lacar Lecidere, Dili",
    locationLat: -8.5590,
    locationLng: 125.5620,
    openingHours: "Tue-Sat: 9AM-6PM",
    aboutUs: "Professional hair cutting, coloring, and styling. Bridal makeup services available.",
    tags: "salon,hair,beauty,bridal",
    likes: 56,
    saves: 19,
    views: 678,
    verifiedBadge: 0,
    socialLinks: JSON.stringify({ instagram: "@salonmariadili" }),
    createdAt: now - 86400 * 120,
    updatedAt: now - 86400 * 5,
  },

  // Automotive
  {
    id: "biz-auto-repair",
    title: "Timor Auto Repair",
    slug: "timor-auto-repair",
    description: "Professional vehicle repair and maintenance",
    ownerId: "owner-13",
    categoryId: "repair-shops",
    status: "published",
    contactName: "Joaquim Santos",
    contactNumber: "77007890",
    countryCode: "+670",
    email: "auto.timor@gmail.com",
    address: "Hera Industrial Zone, Dili",
    locationLat: -8.5234,
    locationLng: 125.5432,
    openingHours: "Mon-Sat: 8AM-5PM",
    aboutUs: "Engine repair, oil change, tire service, and full vehicle maintenance.",
    tags: "auto,repair,mechanic,maintenance",
    likes: 45,
    saves: 12,
    views: 456,
    verifiedBadge: 0,
    socialLinks: JSON.stringify({}),
    createdAt: now - 86400 * 200,
    updatedAt: now - 86400 * 15,
  },
  {
    id: "biz-shell-station",
    title: "Shell Comoro",
    slug: "shell-comoro",
    description: "Fuel station and convenience store",
    ownerId: "owner-14",
    categoryId: "gas-stations",
    status: "published",
    contactName: "Manager",
    contactNumber: "77001111",
    countryCode: "+670",
    email: "",
    address: "Comoro Road, Dili",
    locationLat: -8.5456,
    locationLng: 125.5578,
    openingHours: "24/7",
    aboutUs: "Shell fuel station with convenience store. Air, water, and tire inflation available.",
    tags: "fuel,gas,convenience,24/7",
    likes: 89,
    saves: 8,
    views: 2340,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({}),
    createdAt: now - 86400 * 800,
    updatedAt: now - 86400 * 30,
  },

  // Retail & Shops
  {
    id: "biz-supermarket-matavia",
    title: "Supermercado Matavia",
    slug: "supermercado-matavia",
    description: "Large supermarket with imported goods",
    ownerId: "owner-15",
    categoryId: "supermarkets",
    status: "published",
    contactName: "Manuel da Costa",
    contactNumber: "77009999",
    countryCode: "+670",
    email: "matavia.supermarket@gmail.com",
    address: "Matavia, Dili",
    locationLat: -8.5123,
    locationLng: 125.5512,
    openingHours: "Daily: 7AM-9PM",
    aboutUs: "Wide selection of local and imported products. Fresh produce, household items, and beverages.",
    tags: "supermarket,grocery,imported goods",
    likes: 178,
    saves: 34,
    views: 2890,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "SupermercadoMatavia" }),
    createdAt: now - 86400 * 600,
    updatedAt: now - 86400 * 3,
  },
  {
    id: "biz-toko-souvenir",
    title: "Timor Souvenir Shop",
    slug: "timor-souvenir-shop",
    description: "Authentic Timorese handicrafts and souvenirs",
    ownerId: "owner-16",
    categoryId: "local-crafts",
    status: "published",
    contactName: "Rosa Fernandes",
    contactNumber: "77003456",
    countryCode: "+670",
    email: "timorsouvenir@gmail.com",
    address: "Arte Moris, Dili",
    locationLat: -8.4789,
    locationLng: 125.5890,
    openingHours: "Daily: 9AM-5PM",
    aboutUs: "Hand-woven textiles, carved wood, and traditional Timorese artifacts.",
    tags: "souvenir,handicraft,traditional,textiles",
    likes: 123,
    saves: 67,
    views: 1890,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ instagram: "@timorsouvenir" }),
    createdAt: now - 86400 * 400,
    updatedAt: now - 86400 * 7,
  },

  // Banking & Finance
  {
    id: "biz-bancatimu",
    title: "Banca Timor",
    slug: "banca-timor",
    description: "Microfinance institution supporting local businesses",
    ownerId: "owner-17",
    categoryId: "banks",
    status: "published",
    contactName: "Director",
    contactNumber: "77001122",
    countryCode: "+670",
    email: "info@bancatimu.tl",
    address: "Avenida dos Direitos Humanos, Dili",
    locationLat: -8.5612,
    locationLng: 125.5634,
    openingHours: "Mon-Fri: 8AM-3PM",
    aboutUs: "Microfinance services for small businesses and entrepreneurs. Loans and savings accounts.",
    tags: "bank,finance,microfinance,business loan",
    likes: 67,
    saves: 23,
    views: 789,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({}),
    createdAt: now - 86400 * 500,
    updatedAt: now - 86400 * 10,
  },
];

export default businesses;
