/**
 * Listings Seed Data
 * TimorUp (2026-05-21)
 *
 * 25 realistic Timor-Leste classified ads
 * Categories: Jobs, Vehicles, Property, For Sale, Services, Community
 */

const now = Math.floor(Date.now() / 1000);

// Helper to generate expiresAt (listing 7天试用期)
function expiresAt(daysFromNow = 7) {
  return now + 86400 * daysFromNow;
}

export const listings = [
  // ===== JOBS (5) =====
  {
    id: "listing-job-teacher-1",
    title: "English Teacher Wanted - International School",
    slug: "english-teacher-international-school",
    ownerId: "user-1",
    categoryId: "teaching",
    status: "published",
    description: "International school in Dili seeking qualified English teacher for primary grades. Must have teaching certification and 2+ years experience.",
    priceAmount: 1200.00,
    priceUnit: "USD/month",
    condition: null,
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Maria Santos",
    contactNumber: "77001111",
    countryCode: "+670",
    email: "teach@dili-school.tl",
    imageIds: null,
    tags: "english,teacher,international,school",
    likes: 45,
    saves: 23,
    views: 567,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ jobType: "full-time", experience: "2+ years", qualification: "TEFL/CELTA" }),
    createdAt: now - 86400 * 5,
    updatedAt: now - 86400 * 2,
  },
  {
    id: "listing-job-accountant-1",
    title: "Accountant needed for Audit Firm",
    slug: "accountant-audit-firm-dili",
    ownerId: "user-2",
    categoryId: "finance",
    status: "published",
    description: "Growing audit firm seeks experienced accountant. Responsibilities include bookkeeping, tax preparation, and client liaison.",
    priceAmount: 800.00,
    priceUnit: "USD/month",
    condition: null,
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Carlos til",
    contactNumber: "77002222",
    countryCode: "+670",
    email: "careers@audit-tl.com",
    imageIds: null,
    tags: "accountant,audit,finance,bookkeeping",
    likes: 34,
    saves: 18,
    views: 345,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ jobType: "full-time", experience: "3+ years", qualification: "ACCA/CPA preferred" }),
    createdAt: now - 86400 * 3,
    updatedAt: now - 86400 * 1,
  },
  {
    id: "listing-job-driver-1",
    title: "Driver Needed - Logistics Company",
    slug: "driver-logistics-company",
    ownerId: "user-3",
    categoryId: "drivers",
    status: "published",
    description: "Reliable driver needed for delivery truck. Must have valid Timor-Leste license and clean driving record.",
    priceAmount: 500.00,
    priceUnit: "USD/month",
    condition: null,
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Joaquim til",
    contactNumber: "77003333",
    countryCode: "+670",
    email: "driver@logistics.tl",
    imageIds: null,
    tags: "driver,logistics,delivery,truck",
    likes: 67,
    saves: 12,
    views: 890,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 1,
    featuredUntil: expiresAt(3),
    extraData: JSON.stringify({ jobType: "full-time", license: "Class B", experience: "2+ years" }),
    createdAt: now - 86400 * 2,
    updatedAt: now - 86400 * 1,
  },
  {
    id: "listing-job-chef-1",
    title: "Head Chef - Beach Resort Restaurant",
    slug: "head-chef-beach-resort",
    ownerId: "user-4",
    categoryId: "hospitality",
    status: "published",
    description: "Beach resort restaurant seeking experienced head chef. International cuisine, live kitchen, competitive salary plus accommodation.",
    priceAmount: 1500.00,
    priceUnit: "USD/month",
    condition: null,
    location: "Dili",
    locationLat: -8.4789,
    locationLng: 125.5890,
    contactName: "Ana til",
    contactNumber: "77004444",
    countryCode: "+670",
    email: "jobs@beachresort.tl",
    imageIds: null,
    tags: "chef,restaurant,beach resort,hospitality",
    likes: 89,
    saves: 45,
    views: 1230,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 1,
    featuredUntil: expiresAt(5),
    extraData: JSON.stringify({ jobType: "full-time", accommodation: true, experience: "5+ years" }),
    createdAt: now - 86400 * 1,
    updatedAt: now - 86400 * 0,
  },
  {
    id: "listing-job-ngo-1",
    title: "Project Coordinator - NGO",
    slug: "project-coordinator-ngo-dili",
    ownerId: "user-5",
    categoryId: "ngo",
    status: "published",
    description: "International NGO seeks project coordinator for community development programs. Master's degree preferred, 4+ years relevant experience.",
    priceAmount: 1800.00,
    priceUnit: "USD/month",
    condition: null,
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "HR til",
    contactNumber: "77005555",
    countryCode: "+670",
    email: "recruitment@ngotl.org",
    imageIds: null,
    tags: "ngo,project coordinator,development,community",
    likes: 56,
    saves: 34,
    views: 678,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ jobType: "contract", degree: "Master's preferred", experience: "4+ years" }),
    createdAt: now - 86400 * 4,
    updatedAt: now - 86400 * 2,
  },

  // ===== VEHICLES (5) =====
  {
    id: "listing-vehicle-toyota-1",
    title: "Toyota Hilux 2022 - Low Mileage",
    slug: "toyota-hilux-2022-dili",
    ownerId: "user-6",
    categoryId: "cars",
    status: "published",
    description: "Excellent condition Toyota Hilux 4x4, 2022 model. Only 45,000km. Full service history. Automatic transmission, diesel engine.",
    priceAmount: 28000.00,
    priceUnit: "USD",
    condition: "excellent",
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Rui til",
    contactNumber: "77006666",
    countryCode: "+670",
    email: "toyota.sale@gmail.com",
    imageIds: null,
    tags: "toyota,hilux,4x4,truck,diesel",
    likes: 123,
    saves: 56,
    views: 2340,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 1,
    featuredUntil: expiresAt(4),
    extraData: JSON.stringify({ make: "Toyota", model: "Hilux", year: 2022, mileage: 45000, fuel: "diesel", transmission: "automatic" }),
    createdAt: now - 86400 * 6,
    updatedAt: now - 86400 * 2,
  },
  {
    id: "listing-vehicle-honda-1",
    title: "Honda PCX 150 Scooter - Great Deal",
    slug: "honda-pcx-150-scooter",
    ownerId: "user-7",
    categoryId: "motorcycles",
    status: "published",
    description: "Reliable Honda PCX 150 scooter, perfect for Dili traffic. Low fuel consumption, automatic, great condition.",
    priceAmount: 3500.00,
    priceUnit: "USD",
    condition: "good",
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Paulo til",
    contactNumber: "77007777",
    countryCode: "+670",
    email: "scooter.sale.tl@gmail.com",
    imageIds: null,
    tags: "honda,pcx,scooter,motorcycle,automatic",
    likes: 78,
    saves: 34,
    views: 1560,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ make: "Honda", model: "PCX 150", year: 2021, mileage: 12000, fuel: "petrol" }),
    createdAt: now - 86400 * 3,
    updatedAt: now - 86400 * 1,
  },
  {
    id: "listing-vehicle-landcruiser-1",
    title: "Toyota Land Cruiser 200 Series",
    slug: "toyota-land-cruiser-200-dili",
    ownerId: "user-8",
    categoryId: "cars",
    status: "published",
    description: "Premium Land Cruiser 200 series, V8 diesel. Top model with leather seats, sunroof, and full option package.",
    priceAmount: 45000.00,
    priceUnit: "USD",
    condition: "excellent",
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Luis til",
    contactNumber: "77008888",
    countryCode: "+670",
    email: "landcruiser.sale@gmail.com",
    imageIds: null,
    tags: "toyota,land cruiser,suv,premium,v8",
    likes: 234,
    saves: 89,
    views: 3450,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 1,
    featuredUntil: expiresAt(6),
    extraData: JSON.stringify({ make: "Toyota", model: "Land Cruiser 200", year: 2021, mileage: 35000, fuel: "diesel" }),
    createdAt: now - 86400 * 8,
    updatedAt: now - 86400 * 3,
  },
  {
    id: "listing-vehicle-van-1",
    title: "Toyota HiAce Van - 12 Seater",
    slug: "toyota-hiace-van-12-seater",
    ownerId: "user-9",
    categoryId: "vans",
    status: "published",
    description: "Spacious Toyota HiAce van, 12 seats. Perfect for shuttle service or large family. Diesel, manual transmission.",
    priceAmount: 18000.00,
    priceUnit: "USD",
    condition: "good",
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Manuel til",
    contactNumber: "77009999",
    countryCode: "+670",
    email: "vanforsale.tl@gmail.com",
    imageIds: null,
    tags: "toyota,hiace,van,shuttle,12 seater",
    likes: 67,
    saves: 23,
    views: 1230,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ make: "Toyota", model: "HiAce", year: 2019, mileage: 78000, fuel: "diesel", seats: 12 }),
    createdAt: now - 86400 * 5,
    updatedAt: now - 86400 * 2,
  },
  {
    id: "listing-vehicle-utv-1",
    title: "Yamaha Quad Bike - Off Road",
    slug: "yamaha-quad-bike-offroad",
    ownerId: "user-10",
    categoryId: "other-vehicles",
    status: "published",
    description: "Yamaha YFZ450 quad bike, great for farm or off-road adventures. Recently serviced, new tires.",
    priceAmount: 4500.00,
    priceUnit: "USD",
    condition: "good",
    location: "Aileu",
    locationLat: -8.7306,
    locationLng: 125.4044,
    contactName: "Joao til",
    contactNumber: "77001010",
    countryCode: "+670",
    email: "quadbike.tl@gmail.com",
    imageIds: null,
    tags: "yamaha,quad,bike,offroad,farm",
    likes: 34,
    saves: 12,
    views: 567,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ make: "Yamaha", model: "YFZ450", year: 2020, condition: "off-road" }),
    createdAt: now - 86400 * 2,
    updatedAt: now - 86400 * 1,
  },

  // ===== PROPERTY (5) =====
  {
    id: "listing-property-apartment-1",
    title: "Modern 2BR Apartment - Near Beach",
    slug: "modern-2br-apartment-near-beach",
    ownerId: "user-11",
    categoryId: "apartments",
    status: "published",
    description: "Fully furnished 2 bedroom apartment with ocean view. AC in all rooms, hot water, fully equipped kitchen. Security 24/7.",
    priceAmount: 600.00,
    priceUnit: "USD/month",
    condition: null,
    location: "Beach Road, Dili",
    locationLat: -8.4833,
    locationLng: 125.5856,
    contactName: "Maria til",
    contactNumber: "77001212",
    countryCode: "+670",
    email: "apartment.rent.tl@gmail.com",
    imageIds: null,
    tags: "apartment,2 bedroom,furnished,beach,near",
    likes: 89,
    saves: 45,
    views: 2340,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 1,
    featuredUntil: expiresAt(4),
    extraData: JSON.stringify({ bedrooms: 2, bathrooms: 1, furnished: true, parking: true }),
    createdAt: now - 86400 * 7,
    updatedAt: now - 86400 * 3,
  },
  {
    id: "listing-property-house-1",
    title: "3 Bedroom House - Gic facility",
    slug: "3-bedroom-house-gic",
    ownerId: "user-12",
    categoryId: "houses",
    status: "published",
    description: "Spacious 3 bedroom house in quiet Gic area. Large garden, garage, fully fenced. Water tank and generator included.",
    priceAmount: 800.00,
    priceUnit: "USD/month",
    condition: null,
    location: "Gic, Dili",
    locationLat: -8.5345,
    locationLng: 125.5523,
    contactName: "Antonio til",
    contactNumber: "77001313",
    countryCode: "+670",
    email: "house.rent.tl@gmail.com",
    imageIds: null,
    tags: "house,3 bedroom,garden,garage,fenced",
    likes: 67,
    saves: 34,
    views: 1780,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ bedrooms: 3, bathrooms: 2, furnished: false, landSize: "500m2" }),
    createdAt: now - 86400 * 4,
    updatedAt: now - 86400 * 2,
  },
  {
    id: "listing-property-land-1",
    title: "Commercial Land - Main Road",
    slug: "commercial-land-main-road-dili",
    ownerId: "user-13",
    categoryId: "land",
    status: "published",
    description: "Prime commercial land on main road. 1000m2, level terrain, all utilities available. Perfect for shop or office.",
    priceAmount: 150000.00,
    priceUnit: "USD",
    condition: null,
    location: "Comoro Road, Dili",
    locationLat: -8.5456,
    locationLng: 125.5578,
    contactName: "Fernanda til",
    contactNumber: "77001414",
    countryCode: "+670",
    email: "land.sale.tl@gmail.com",
    imageIds: null,
    tags: "land,commercial,main road,1000m2,prime",
    likes: 134,
    saves: 56,
    views: 2890,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 1,
    featuredUntil: expiresAt(5),
    extraData: JSON.stringify({ landSize: "1000m2", zoning: "commercial", utilities: ["electricity", "water", "road access"] }),
    createdAt: now - 86400 * 10,
    updatedAt: now - 86400 * 5,
  },
  {
    id: "listing-property-office-1",
    title: "Office Space - Trade Tower",
    slug: "office-space-trade-tower-dili",
    ownerId: "user-14",
    categoryId: "commercial",
    status: "published",
    description: "Modern office space in Trade Tower building. 80m2, lift access, parking included. Long term lease available.",
    priceAmount: 1200.00,
    priceUnit: "USD/month",
    condition: null,
    location: "Trade Tower, Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Carlos til",
    contactNumber: "77001515",
    countryCode: "+670",
    email: "office.rent.tl@gmail.com",
    imageIds: null,
    tags: "office,commercial,trade tower,modern,80m2",
    likes: 56,
    saves: 23,
    views: 1230,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ size: "80m2", parking: true, lift: true }),
    createdAt: now - 86400 * 6,
    updatedAt: now - 86400 * 3,
  },
  {
    id: "listing-property-warehouse-1",
    title: "Warehouse - Hera Industrial Zone",
    slug: "warehouse-hera-industrial-zone",
    ownerId: "user-15",
    categoryId: "industrial",
    status: "published",
    description: "Large warehouse in Hera Industrial Zone. 500m2, high ceiling, loading dock. Ideal for storage or light manufacturing.",
    priceAmount: 2500.00,
    priceUnit: "USD/month",
    condition: null,
    location: "Hera Industrial Zone, Dili",
    locationLat: -8.5234,
    locationLng: 125.5432,
    contactName: "Pedro til",
    contactNumber: "77001616",
    countryCode: "+670",
    email: "warehouse.rent.tl@gmail.com",
    imageIds: null,
    tags: "warehouse,industrial,hera,storage,500m2",
    likes: 45,
    saves: 18,
    views: 890,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ size: "500m2", ceilingHeight: "6m", loadingDock: true }),
    createdAt: now - 86400 * 8,
    updatedAt: now - 86400 * 4,
  },

  // ===== FOR SALE (5) =====
  {
    id: "listing-sale-fridge-1",
    title: "Samsung Double Door Fridge - New",
    slug: "samsung-double-door-fridge-dili",
    ownerId: "user-16",
    categoryId: "electronics",
    status: "published",
    description: "Brand new Samsung double door refrigerator. Inverter technology, energy efficient. Full warranty included.",
    priceAmount: 850.00,
    priceUnit: "USD",
    condition: "new",
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Ana til",
    contactNumber: "77001717",
    countryCode: "+670",
    email: "electronics.sale.tl@gmail.com",
    imageIds: null,
    tags: "samsung,fridge,refrigerator,electronics,new",
    likes: 34,
    saves: 12,
    views: 567,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ brand: "Samsung", type: "double door", warranty: "2 years" }),
    createdAt: now - 86400 * 3,
    updatedAt: now - 86400 * 1,
  },
  {
    id: "listing-sale-sofa-1",
    title: "L-Shape Sofa Set - Like New",
    slug: "l-shape-sofa-set-like-new",
    ownerId: "user-17",
    categoryId: "furniture",
    status: "published",
    description: "Comfortable L-shape sofa set, gray color. Only 6 months old, like new condition. Moving sale.",
    priceAmount: 450.00,
    priceUnit: "USD",
    condition: "like-new",
    location: "Lacar Lecidere, Dili",
    locationLat: -8.5590,
    locationLng: 125.5620,
    contactName: "Joaquim til",
    contactNumber: "77001818",
    countryCode: "+670",
    email: "furniture.sale.tl@gmail.com",
    imageIds: null,
    tags: "sofa,furniture,l-shape,gray,like new",
    likes: 23,
    saves: 8,
    views: 345,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ type: "L-shape", color: "gray", material: "fabric" }),
    createdAt: now - 86400 * 2,
    updatedAt: now - 86400 * 1,
  },
  {
    id: "listing-sale-bike-1",
    title: "Mountain Bike - Trek Marlin 7",
    slug: "trek-marlin-7-mountain-bike",
    ownerId: "user-18",
    categoryId: "sports",
    status: "published",
    description: "Trek Marlin 7 mountain bike, size M frame. Aluminum frame, 29\" wheels. Perfect for Timor trails.",
    priceAmount: 650.00,
    priceUnit: "USD",
    condition: "good",
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Bruno til",
    contactNumber: "77001919",
    countryCode: "+670",
    email: "bike.sale.tl@gmail.com",
    imageIds: null,
    tags: "trek,mountain bike,cycling,sports,trails",
    likes: 45,
    saves: 15,
    views: 678,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ brand: "Trek", model: "Marlin 7", size: "M", wheels: "29 inch" }),
    createdAt: now - 86400 * 4,
    updatedAt: now - 86400 * 2,
  },
  {
    id: "listing-sale-tv-1",
    title: "LG 55\" Smart TV - 4K",
    slug: "lg-55-inch-smart-tv-4k",
    ownerId: "user-19",
    categoryId: "electronics",
    status: "published",
    description: "LG 55 inch 4K Smart TV. WebOS, built-in WiFi, HDR. Perfect condition with original remote and stand.",
    priceAmount: 550.00,
    priceUnit: "USD",
    condition: "good",
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Maria til",
    contactNumber: "77002020",
    countryCode: "+670",
    email: "tv.sale.tl@gmail.com",
    imageIds: null,
    tags: "lg,smart tv,55 inch,4k,television",
    likes: 56,
    saves: 23,
    views: 890,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 1,
    featuredUntil: expiresAt(2),
    extraData: JSON.stringify({ brand: "LG", size: "55 inch", resolution: "4K", smartTV: true }),
    createdAt: now - 86400 * 5,
    updatedAt: now - 86400 * 2,
  },
  {
    id: "listing-sale-sandalwood-1",
    title: "Sandalwood Carving - Traditional Art",
    slug: "sandalwood-carving-traditional",
    ownerId: "user-20",
    categoryId: "arts",
    status: "published",
    description: "Authentic Timorese sandalwood carving. Traditional crocodile design, hand-crafted by local artisan. Certificate of authenticity included.",
    priceAmount: 350.00,
    priceUnit: "USD",
    condition: "new",
    location: "Arte Moris, Dili",
    locationLat: -8.4789,
    locationLng: 125.5890,
    contactName: "Rosa til",
    contactNumber: "77002121",
    countryCode: "+670",
    email: "art.tl@gmail.com",
    imageIds: null,
    tags: "sandalwood,carving,traditional,art,crocodile",
    likes: 67,
    saves: 34,
    views: 1120,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ material: "sandalwood", style: "traditional", origin: "Timor-Leste" }),
    createdAt: now - 86400 * 6,
    updatedAt: now - 86400 * 3,
  },

  // ===== SERVICES (5) =====
  {
    id: "listing-service-photo-1",
    title: "Wedding Photography - Full Day Coverage",
    slug: "wedding-photography-full-day-dili",
    ownerId: "user-21",
    categoryId: "photography",
    status: "published",
    description: "Professional wedding photographer with 8 years experience. Full day coverage, 500+ edited photos, 2 photographers.",
    priceAmount: 800.00,
    priceUnit: "USD",
    condition: null,
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Roberto til",
    contactNumber: "77002222",
    countryCode: "+670",
    email: "photo.tl@gmail.com",
    imageIds: null,
    tags: "wedding,photography,professional,events,coverage",
    likes: 89,
    saves: 45,
    views: 1560,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 1,
    featuredUntil: expiresAt(3),
    extraData: JSON.stringify({ type: "event", coverage: "full day", photos: "500+", photographers: 2 }),
    createdAt: now - 86400 * 8,
    updatedAt: now - 86400 * 4,
  },
  {
    id: "listing-service-plumber-1",
    title: "Professional Plumbing Service",
    slug: "professional-plumbing-service-dili",
    ownerId: "user-22",
    categoryId: "home-repair",
    status: "published",
    description: "Licensed plumber for all residential and commercial work. Piping, installation, repairs, and emergency service available.",
    priceAmount: 50.00,
    priceUnit: "USD/hour",
    condition: null,
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Afonso til",
    contactNumber: "77002323",
    countryCode: "+670",
    email: "plumber.dili@gmail.com",
    imageIds: null,
    tags: "plumber,plumbing,repair,installation,emergency",
    likes: 123,
    saves: 56,
    views: 2340,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ service: "repair", emergency: true, licensed: true }),
    createdAt: now - 86400 * 10,
    updatedAt: now - 86400 * 5,
  },
  {
    id: "listing-service-tutor-1",
    title: "Math & Science Tutor - Home Visits",
    slug: "math-science-tutor-home-visits",
    ownerId: "user-23",
    categoryId: "tutoring",
    status: "published",
    description: "Experienced tutor for primary and secondary students. Math, Physics, Chemistry. Home visits or online sessions available.",
    priceAmount: 25.00,
    priceUnit: "USD/hour",
    condition: null,
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Dr. Fatima til",
    contactNumber: "77002424",
    countryCode: "+670",
    email: "tutor.tl@gmail.com",
    imageIds: null,
    tags: "tutor,math,physics,chemistry,education",
    likes: 67,
    saves: 34,
    views: 1230,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ subjects: ["math", "physics", "chemistry"], level: "primary-secondary", online: true }),
    createdAt: now - 86400 * 7,
    updatedAt: now - 86400 * 3,
  },
  {
    id: "listing-service-cleaning-1",
    title: "Deep Cleaning Service - Homes & Offices",
    slug: "deep-cleaning-service-dili",
    ownerId: "user-24",
    categoryId: "cleaning",
    status: "published",
    description: "Professional deep cleaning for homes and offices. Including windows, carpets, upholstery. Eco-friendly products used.",
    priceAmount: 80.00,
    priceUnit: "USD",
    condition: null,
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Julia til",
    contactNumber: "77002525",
    countryCode: "+670",
    email: "clean.tl@gmail.com",
    imageIds: null,
    tags: "cleaning,deep clean,house,office,professional",
    likes: 89,
    saves: 45,
    views: 1780,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ type: "deep cleaning", ecoFriendly: true, includes: ["windows", "carpets", "upholstery"] }),
    createdAt: now - 86400 * 5,
    updatedAt: now - 86400 * 2,
  },
  {
    id: "listing-service-moving-1",
    title: "Moving & Relocation Service",
    slug: "moving-relocation-service-dili",
    ownerId: "user-25",
    categoryId: "moving",
    status: "published",
    description: "Complete moving service: packing, loading, transport, unloading. Local and long distance. Free quote on request.",
    priceAmount: 150.00,
    priceUnit: "USD",
    condition: null,
    location: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    contactName: "Jose til",
    contactNumber: "77002626",
    countryCode: "+670",
    email: "moving.tl@gmail.com",
    imageIds: null,
    tags: "moving,relocation,transport,pack,delivery",
    likes: 56,
    saves: 23,
    views: 890,
    expiresAt: expiresAt(7),
    lastRenewedAt: null,
    featured: 0,
    featuredUntil: null,
    extraData: JSON.stringify({ service: "full service", includes: ["packing", "loading", "transport", "unloading"] }),
    createdAt: now - 86400 * 3,
    updatedAt: now - 86400 * 1,
  },
];

export default listings;