/**
 * Non-Profits Seed Data
 * TimorUp (2026-05-21)
 *
 * 10 realistic Timor-Leste NGOs and non-profit organizations
 */

const now = Math.floor(Date.now() / 1000);

export const nonProfits = [
  // ===== Health & Medical =====
  {
    id: "ngo-hopital-bairo-pite",
    title: "Hospital Bairo Pite",
    slug: "hospital-bairo-pite",
    ownerId: "ngo-admin-1",
    categoryId: "healthcare",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Dr. Dan Silva",
    contactNumber: "77001234",
    countryCode: "+670",
    yearOfEstablishment: 1999,
    email: "info@hbp-tl.org",
    address: "Bairo Pite, Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "Mon-Sat: 8AM-5PM",
    aboutUs: "Community-run hospital providing affordable healthcare to all Timorese. Services include emergency care, maternal health, and general medicine.",
    tags: "healthcare,hospital,medical,community",
    likes: 456,
    saves: 123,
    views: 5670,
    registrationUrl: "https://www.hbp-tl.org",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "HospitalBairoPite", instagram: "@hbptl" }),
    createdAt: now - 86400 * 1500,
    updatedAt: now - 86400 * 10,
  },
  {
    id: "ngo-maluk Timor",
    title: "Maluk Timor",
    slug: "maluk-timor",
    ownerId: "ngo-admin-2",
    categoryId: "healthcare",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Dr. Joanita",
    contactNumber: "77002345",
    countryCode: "+670",
    yearOfEstablishment: 2010,
    email: "contact@maluktimor.org",
    address: "Target, Dili",
    locationLat: -8.5512,
    locationLng: 125.5645,
    openingHours: "Mon-Fri: 8AM-4PM",
    aboutUs: "Heart health organization specializing in cardiology and cardiovascular care for Timor-Leste.",
    tags: "health,cardiology,heart,medical",
    likes: 234,
    saves: 89,
    views: 2890,
    registrationUrl: "https://maluktimor.org",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ instagram: "@maluktimor", facebook: "MalukTimor" }),
    createdAt: now - 86400 * 1200,
    updatedAt: now - 86400 * 15,
  },

  // ===== Education & Youth =====
  {
    id: "ngo-fundacao Cheia",
    title: "Fundasaun Cheia",
    slug: "fundasaun-cheia",
    ownerId: "ngo-admin-3",
    categoryId: "education",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Ana Belo",
    contactNumber: "77003456",
    countryCode: "+670",
    yearOfEstablishment: 2008,
    email: "info@fundasauncheira.tl",
    address: "Lospalos",
    locationLat: -8.5891,
    locationLng: 126.9878,
    openingHours: "Mon-Fri: 7AM-5PM",
    aboutUs: "Non-profit focused on education for children in remote areas. Programs include literacy, numeracy, and life skills training.",
    tags: "education,children,youth,remote areas",
    likes: 178,
    saves: 67,
    views: 1890,
    registrationUrl: null,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "FundasaunCheia" }),
    createdAt: now - 86400 * 1000,
    updatedAt: now - 86400 * 20,
  },
  {
    id: "ngo-passared",
    title: "Passaredo",
    slug: "passaredo",
    ownerId: "ngo-admin-4",
    categoryId: "education",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Fr. Jose",
    contactNumber: "77004567",
    countryCode: "+670",
    yearOfEstablishment: 1995,
    email: "passaredo@tl.com",
    address: "Aileu",
    locationLat: -8.7306,
    locationLng: 125.4044,
    openingHours: "Mon-Sat: 8AM-4PM",
    aboutUs: "Foundation operating schools and vocational training centers across Timor-Leste.",
    tags: "education,vocational,schools,training",
    likes: 289,
    saves: 98,
    views: 3450,
    registrationUrl: "https://passaredo.org",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "PassaredoTL" }),
    createdAt: now - 86400 * 1800,
    updatedAt: now - 86400 * 25,
  },

  // ===== Environment & Agriculture =====
  {
    id: "ngo-birds-timor",
    title: "Timor-Leste Birds Program",
    slug: "birds-tl",
    ownerId: "ngo-admin-5",
    categoryId: "environment",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Rui Oliveira",
    contactNumber: "77005678",
    countryCode: "+670",
    yearOfEstablishment: 2015,
    email: "info@birds-tl.org",
    address: "Lospalos",
    locationLat: -8.5891,
    locationLng: 126.9878,
    openingHours: "Mon-Fri: 9AM-5PM",
    aboutUs: "Conservation program protecting endangered bird species and their habitats in Timor-Leste.",
    tags: "environment,birds,conservation,wildlife",
    likes: 134,
    saves: 56,
    views: 1560,
    registrationUrl: "https://birds Timor.org",
    verifiedBadge: 0,
    socialLinks: JSON.stringify({ instagram: "@birdstimor" }),
    createdAt: now - 86400 * 800,
    updatedAt: now - 86400 * 30,
  },
  {
    id: "ngo-joan-gomes",
    title: "Fundasaun Joan Gomes",
    slug: "fundasaun-joan-gomes",
    ownerId: "ngo-admin-6",
    categoryId: "agriculture",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Luis da Costa",
    contactNumber: "77006789",
    countryCode: "+670",
    yearOfEstablishment: 2012,
    email: "fundasaunjgomes@gmail.com",
    address: "Aileu",
    locationLat: -8.7306,
    locationLng: 125.4044,
    openingHours: "Mon-Fri: 8AM-4PM",
    aboutUs: "Agricultural foundation promoting sustainable farming and food security in rural communities.",
    tags: "agriculture,farming,food security,rural",
    likes: 167,
    saves: 78,
    views: 2120,
    registrationUrl: null,
    verifiedBadge: 0,
    socialLinks: JSON.stringify({ facebook: "FundasaunJoanGomes" }),
    createdAt: now - 86400 * 900,
    updatedAt: now - 86400 * 35,
  },

  // ===== Women & Community =====
  {
    id: "ngo-feto-foin",
    title: "Feto Foin",
    slug: "feto-foin",
    ownerId: "ngo-admin-7",
    categoryId: "women",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Maria Ximenes",
    contactNumber: "77007890",
    countryCode: "+670",
    yearOfEstablishment: 2005,
    email: "fetufoin@gmail.com",
    address: "Comoro, Dili",
    locationLat: -8.5456,
    locationLng: 125.5578,
    openingHours: "Mon-Fri: 9AM-5PM",
    aboutUs: "Women's organization empowering Timorese women through education, microfinance, and leadership programs.",
    tags: "women,empowerment,education,microfinance",
    likes: 298,
    saves: 145,
    views: 4230,
    registrationUrl: null,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ instagram: "@fetofoin", facebook: "FetoFoinTL" }),
    createdAt: now - 86400 * 1400,
    updatedAt: now - 86400 * 12,
  },
  {
    id: "ngo-moris-fuin",
    title: "Moris Fuin",
    slug: "moris-fuin",
    ownerId: "ngo-admin-8",
    categoryId: "community",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Paulo Gusmao",
    contactNumber: "77008901",
    countryCode: "+670",
    yearOfEstablishment: 2018,
    email: "moris.fuin.tl@gmail.com",
    address: "Viqueque",
    locationLat: -8.8612,
    locationLng: 126.3512,
    openingHours: "Mon-Sat: 8AM-5PM",
    aboutUs: "Community development organization focused on youth empowerment and cultural preservation.",
    tags: "youth,community,culture,development",
    likes: 89,
    saves: 34,
    views: 980,
    registrationUrl: null,
    verifiedBadge: 0,
    socialLinks: JSON.stringify({ facebook: "MorisFuin" }),
    createdAt: now - 86400 * 600,
    updatedAt: now - 86400 * 40,
  },

  // ===== Disability & Social Services =====
  {
    id: "ngo-habilitas",
    title: "Habilitas Timor-Leste",
    slug: "habilitas-tl",
    ownerId: "ngo-admin-9",
    categoryId: "disability",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Tomas Soares",
    contactNumber: "77009012",
    countryCode: "+670",
    yearOfEstablishment: 2007,
    email: "habilitas.tl@gmail.com",
    address: "Bemori, Dili",
    locationLat: -8.5234,
    locationLng: 125.5432,
    openingHours: "Mon-Fri: 8AM-5PM",
    aboutUs: "Organization advocating for and supporting people with disabilities in Timor-Leste.",
    tags: "disability,inclusion,rights,support",
    likes: 234,
    saves: 98,
    views: 2780,
    registrationUrl: "https://habilitastl.org",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "HabilitasTL", instagram: "@habilitastl" }),
    createdAt: now - 86400 * 1100,
    updatedAt: now - 86400 * 18,
  },
  {
    id: "ngo-kdadatak",
    title: "Kdadatak Foundation",
    slug: "kdadatak",
    ownerId: "ngo-admin-10",
    categoryId: "social-services",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Fernanda til",
    contactNumber: "77000123",
    countryCode: "+670",
    yearOfEstablishment: 2014,
    email: "kdadatak.foundation@gmail.com",
    address: "Lospalos",
    locationLat: -8.5891,
    locationLng: 126.9878,
    openingHours: "Mon-Fri: 8AM-4PM",
    aboutUs: "Foundation supporting vulnerable children and families through social services and community programs.",
    tags: "children,family,social services,vulnerable",
    likes: 156,
    saves: 67,
    views: 1890,
    registrationUrl: null,
    verifiedBadge: 0,
    socialLinks: JSON.stringify({ facebook: "KdadatakFoundation" }),
    createdAt: now - 86400 * 850,
    updatedAt: now - 86400 * 22,
  },
];

export default nonProfits;