/**
 * Products Seed Data
 * TimorUp (2026-05-21)
 *
 * 2-3 products per business (~40 products total)
 * 每个 business 有 2-3 个产品/服务
 */

const now = Math.floor(Date.now() / 1000);

export const products = [
  // ===== Café Timor (biz-cafe-timor) =====
  {
    id: "prod-cafe-espresso",
    businessId: "biz-cafe-timor",
    categoryId: "coffee-drinks",
    title: "Espresso",
    slug: "espresso",
    description: "Single shot of Timor-Leste's finest arabica coffee",
    productType: "product",
    priceAmount: 1.50,
    priceUnit: "USD",
    specifications: JSON.stringify({ size: "small", caffeine: "medium", origin: "Ermera" }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 150,
    updatedAt: now - 86400 * 3,
  },
  {
    id: "prod-cafe-cold-brew",
    businessId: "biz-cafe-timor",
    categoryId: "coffee-drinks",
    title: "Cold Brew",
    slug: "cold-brew",
    description: "24-hour steeped cold brew, smooth and refreshing",
    productType: "product",
    priceAmount: 3.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ size: "large", caffeine: "high", served: "iced" }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 140,
    updatedAt: now - 86400 * 5,
  },
  {
    id: "prod-cafe-pastries",
    businessId: "biz-cafe-timor",
    categoryId: "bakery",
    title: "Fresh Pastries",
    slug: "fresh-pastries",
    description: "Assorted freshly baked pastries and croissants",
    productType: "product",
    priceAmount: 2.50,
    priceUnit: "USD",
    specifications: JSON.stringify({ type: "bakery", freshlyBaked: true }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 3,
    createdAt: now - 86400 * 130,
    updatedAt: now - 86400 * 7,
  },

  // ===== Warung Nazar (biz-warung-nazar) =====
  {
    id: "prod-warung-bife-sufe",
    businessId: "biz-warung-nazar",
    categoryId: "timorese-dishes",
    title: "Bife Sufe",
    slug: "bife-sufe",
    description: "Traditional Timorese beef in coconut sauce",
    productType: "product",
    priceAmount: 5.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ cuisine: "Timorese", spiceLevel: "medium", serves: 1 }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 80,
    updatedAt: now - 86400 * 5,
  },
  {
    id: "prod-warung-fish-curry",
    businessId: "biz-warung-nazar",
    categoryId: "timorese-dishes",
    title: "Curry Fish",
    slug: "curry-fish",
    description: "Fresh fish curry with local vegetables",
    productType: "product",
    priceAmount: 6.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ cuisine: "Timorese", fish: "local catch", spiceLevel: "hot" }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 75,
    updatedAt: now - 86400 * 8,
  },
  {
    id: "prod-warung-combo",
    businessId: "biz-warung-nazar",
    categoryId: "meal-deals",
    title: "Rice Plate Combo",
    slug: "rice-plate-combo",
    description: "Rice with choice of meat, vegetables, and soup",
    productType: "product",
    priceAmount: 4.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ includes: ["rice", "protein", "veggies", "soup"] }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 3,
    createdAt: now - 86400 * 70,
    updatedAt: now - 86400 * 10,
  },

  // ===== Burger King Timor (biz-burger-king-dili) =====
  {
    id: "prod-bk-whopper",
    businessId: "biz-burger-king-dili",
    categoryId: "burgers",
    title: "Whopper",
    slug: "whopper",
    description: "Flame-grilled beef patty with fresh toppings",
    productType: "product",
    priceAmount: 6.50,
    priceUnit: "USD",
    specifications: JSON.stringify({ calories: 657, protein: "beef", allergens: ["gluten", "dairy"] }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 300,
    updatedAt: now - 86400 * 20,
  },
  {
    id: "prod-bk-chicken",
    businessId: "biz-burger-king-dili",
    categoryId: "chicken",
    title: "Crispy Chicken Sandwich",
    slug: "crispy-chicken",
    description: "Crispy breaded chicken with mayo and lettuce",
    productType: "product",
    priceAmount: 5.50,
    priceUnit: "USD",
    specifications: JSON.stringify({ calories: 490, protein: "chicken" }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 290,
    updatedAt: now - 86400 * 25,
  },
  {
    id: "prod-bk-combo",
    businessId: "biz-burger-king-dili",
    categoryId: "meal-deals",
    title: "Value Meal",
    slug: "value-meal",
    description: "Burger + fries + drink",
    productType: "product",
    priceAmount: 9.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ includes: ["burger", "fries", "drink"] }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 3,
    createdAt: now - 86400 * 280,
    updatedAt: now - 86400 * 15,
  },

  // ===== Hotel Timor (biz-hotel-timor) =====
  {
    id: "prod-hotel-standard",
    businessId: "biz-hotel-timor",
    categoryId: "rooms",
    title: "Standard Room",
    slug: "standard-room",
    description: "Comfortable room with AC, WiFi, and sea view",
    productType: "product",
    priceAmount: 80.00,
    priceUnit: "USD/night",
    specifications: JSON.stringify({ bed: "double", capacity: 2, amenities: ["AC", "WiFi", "TV", "safe"] }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 600,
    updatedAt: now - 86400 * 30,
  },
  {
    id: "prod-hotel-suite",
    businessId: "biz-hotel-timor",
    categoryId: "rooms",
    title: "Ocean Suite",
    slug: "ocean-suite",
    description: "Luxury suite with panoramic ocean view and balcony",
    productType: "product",
    priceAmount: 150.00,
    priceUnit: "USD/night",
    specifications: JSON.stringify({ bed: "king", capacity: 2, amenities: ["AC", "WiFi", "minibar", "balcony", "jacuzzi"] }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 580,
    updatedAt: now - 86400 * 25,
  },
  {
    id: "prod-hotel-conference",
    businessId: "biz-hotel-timor",
    categoryId: "services",
    title: "Conference Room Rental",
    slug: "conference-room",
    description: "Fully equipped conference room for meetings and events",
    productType: "service",
    priceAmount: 200.00,
    priceUnit: "USD/day",
    specifications: JSON.stringify({ capacity: 50, equipment: ["projector", "whiteboard", "sound system"] }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 3,
    createdAt: now - 86400 * 550,
    updatedAt: now - 86400 * 40,
  },

  // ===== Guesthouse Santa Cruz (biz-guesthouse-santa) =====
  {
    id: "prod-gh-dorm",
    businessId: "biz-guesthouse-santa",
    categoryId: "rooms",
    title: "Dormitory Bed",
    slug: "dormitory-bed",
    description: "Shared dorm room with 4 beds, shared bathroom",
    productType: "product",
    priceAmount: 15.00,
    priceUnit: "USD/night",
    specifications: JSON.stringify({ bed: "single", capacity: 1, shared: true }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 180,
    updatedAt: now - 86400 * 10,
  },
  {
    id: "prod-gh-private",
    businessId: "biz-guesthouse-santa",
    categoryId: "rooms",
    title: "Private Room",
    slug: "private-room",
    description: "Private room with en-suite bathroom and fan",
    productType: "product",
    priceAmount: 25.00,
    priceUnit: "USD/night",
    specifications: JSON.stringify({ bed: "double", capacity: 2, bathroom: "ensuite", fan: true }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 175,
    updatedAt: now - 86400 * 8,
  },

  // ===== Timor Tech Solutions (biz-timor-tech) =====
  {
    id: "prod-tt-web-dev",
    businessId: "biz-timor-tech",
    categoryId: "it-services",
    title: "Website Development",
    slug: "website-development",
    description: "Professional website design and development",
    productType: "service",
    priceAmount: 500.00,
    priceUnit: "USD/project",
    specifications: JSON.stringify({ duration: "2-4 weeks", pages: "up to 10", includes: ["design", "development", "hosting setup"] }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 350,
    updatedAt: now - 86400 * 15,
  },
  {
    id: "prod-tt-consulting",
    businessId: "biz-timor-tech",
    categoryId: "it-services",
    title: "IT Consulting",
    slug: "it-consulting",
    description: "Expert IT advice and system optimization",
    productType: "service",
    priceAmount: 75.00,
    priceUnit: "USD/hour",
    specifications: JSON.stringify({ duration: "per hour", remote: true }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 340,
    updatedAt: now - 86400 * 20,
  },
  {
    id: "prod-tt-support",
    businessId: "biz-timor-tech",
    categoryId: "it-services",
    title: "Tech Support Package",
    slug: "tech-support-package",
    description: "Monthly IT support and maintenance",
    productType: "subscription",
    priceAmount: 200.00,
    priceUnit: "USD/month",
    specifications: JSON.stringify({ hours: 10, remoteSupport: true, priority: "normal" }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 3,
    createdAt: now - 86400 * 330,
    updatedAt: now - 86400 * 5,
  },

  // ===== Phone World Timor (biz-phone-world) =====
  {
    id: "prod-pw-iphone-15",
    businessId: "biz-phone-world",
    categoryId: "phones",
    title: "iPhone 15",
    slug: "iphone-15",
    description: "Latest iPhone with full warranty",
    productType: "product",
    priceAmount: 999.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ storage: "128GB", color: "Black", warranty: "1 year" }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 400,
    updatedAt: now - 86400 * 3,
  },
  {
    id: "prod-pw-samsung-s24",
    businessId: "biz-phone-world",
    categoryId: "phones",
    title: "Samsung S24 Ultra",
    slug: "samsung-s24-ultra",
    description: "Samsung flagship with AI features",
    productType: "product",
    priceAmount: 1099.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ storage: "256GB", color: "Titanium Gray", warranty: "1 year" }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 390,
    updatedAt: now - 86400 * 5,
  },
  {
    id: "prod-pw-repair",
    businessId: "biz-phone-world",
    categoryId: "repair-services",
    title: "Screen Repair",
    slug: "screen-repair",
    description: "Professional screen replacement for all brands",
    productType: "service",
    priceAmount: 30.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ warranty: "3 months", original: true }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 3,
    createdAt: now - 86400 * 380,
    updatedAt: now - 86400 * 2,
  },

  // ===== Timor Dental Clinic (biz-dental-clinic) =====
  {
    id: "prod-dental-checkup",
    businessId: "biz-dental-clinic",
    categoryId: "dental-services",
    title: "Dental Checkup",
    slug: "dental-checkup",
    description: "Complete oral examination and consultation",
    productType: "service",
    priceAmount: 20.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ duration: "30 min", includes: ["examination", "x-ray", "consultation"] }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 250,
    updatedAt: now - 86400 * 10,
  },
  {
    id: "prod-dental-cleaning",
    businessId: "biz-dental-clinic",
    categoryId: "dental-services",
    title: "Teeth Cleaning",
    slug: "teeth-cleaning",
    description: "Professional teeth cleaning and polishing",
    productType: "service",
    priceAmount: 35.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ duration: "45 min", includes: ["cleaning", "polishing", "fluoride"] }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 240,
    updatedAt: now - 86400 * 15,
  },
  {
    id: "prod-dental-filling",
    businessId: "biz-dental-clinic",
    categoryId: "dental-services",
    title: "Tooth Filling",
    slug: "tooth-filling",
    description: "Composite filling for cavities",
    productType: "service",
    priceAmount: 50.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ material: "composite", color: "tooth-colored" }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 3,
    createdAt: now - 86400 * 230,
    updatedAt: now - 86400 * 20,
  },

  // ===== Pharma Plus Dili (biz-pharma-plus) =====
  {
    id: "prod-pharma-paracetamol",
    businessId: "biz-pharma-plus",
    categoryId: "medicines",
    title: "Paracetamol 500mg",
    slug: "paracetamol-500mg",
    description: "Pain reliever and fever reducer",
    productType: "product",
    priceAmount: 2.50,
    priceUnit: "USD",
    specifications: JSON.stringify({ dosage: "500mg", quantity: "20 tablets", generic: true }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 400,
    updatedAt: now - 86400 * 5,
  },
  {
    id: "prod-pharma-vitamins",
    businessId: "biz-pharma-plus",
    categoryId: "health-products",
    title: "Multivitamin Pack",
    slug: "multivitamin-pack",
    description: "Daily vitamin supplements for immune support",
    productType: "product",
    priceAmount: 15.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ duration: "30 days", dosage: "1 daily" }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 380,
    updatedAt: now - 86400 * 10,
  },

  // ===== Fitness First Timor (biz-fit-gym) =====
  {
    id: "prod-gym-day-pass",
    businessId: "biz-fit-gym",
    categoryId: "fitness",
    title: "Day Pass",
    slug: "day-pass",
    description: "Single day access to all gym facilities",
    productType: "ticket",
    priceAmount: 5.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ validity: "1 day", includes: ["all equipment", "locker"] }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 150,
    updatedAt: now - 86400 * 5,
  },
  {
    id: "prod-gym-monthly",
    businessId: "biz-fit-gym",
    categoryId: "fitness",
    title: "Monthly Membership",
    slug: "monthly-membership",
    description: "Unlimited gym access for 30 days",
    productType: "subscription",
    priceAmount: 50.00,
    priceUnit: "USD/month",
    specifications: JSON.stringify({ validity: "30 days", includes: ["all equipment", "group classes", "locker"] }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 140,
    updatedAt: now - 86400 * 8,
  },
  {
    id: "prod-gym-personal",
    businessId: "biz-fit-gym",
    categoryId: "personal-training",
    title: "Personal Training Session",
    slug: "personal-training",
    description: "One-on-one training with certified instructor",
    productType: "service",
    priceAmount: 30.00,
    priceUnit: "USD/session",
    specifications: JSON.stringify({ duration: "60 min", includes: ["assessment", "program design"] }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 3,
    createdAt: now - 86400 * 130,
    updatedAt: now - 86400 * 12,
  },

  // ===== English Learning Center Timor (biz-english-center) =====
  {
    id: "prod-english-conversation",
    businessId: "biz-english-center",
    categoryId: "language-courses",
    title: "Conversation Class",
    slug: "conversation-class",
    description: "Weekly conversation practice for intermediate learners",
    productType: "subscription",
    priceAmount: 80.00,
    priceUnit: "USD/month",
    specifications: JSON.stringify({ sessions: 4, duration: "60 min each", level: "intermediate" }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 300,
    updatedAt: now - 86400 * 20,
  },
  {
    id: "prod-english-ielts",
    businessId: "biz-english-center",
    categoryId: "language-courses",
    title: "IELTS Preparation",
    slug: "ielts-preparation",
    description: "Comprehensive IELTS test preparation course",
    productType: "subscription",
    priceAmount: 200.00,
    priceUnit: "USD/month",
    specifications: JSON.stringify({ duration: "8 weeks", includes: ["materials", "mock tests", "feedback"] }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 290,
    updatedAt: now - 86400 * 15,
  },

  // ===== Salon Maria (biz-salon-maria) =====
  {
    id: "prod-salon-haircut",
    businessId: "biz-salon-maria",
    categoryId: "hair-services",
    title: "Women's Haircut",
    slug: "womens-haircut",
    description: "Professional haircut and styling",
    productType: "service",
    priceAmount: 15.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ duration: "45 min", includes: ["wash", "cut", "style"] }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 100,
    updatedAt: now - 86400 * 5,
  },
  {
    id: "prod-salon-color",
    businessId: "biz-salon-maria",
    categoryId: "hair-services",
    title: "Hair Coloring",
    slug: "hair-coloring",
    description: "Full hair coloring with professional products",
    productType: "service",
    priceAmount: 45.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ duration: "2 hours", type: "permanent" }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 90,
    updatedAt: now - 86400 * 10,
  },

  // ===== Timor Auto Repair (biz-auto-repair) =====
  {
    id: "prod-auto-oil-change",
    businessId: "biz-auto-repair",
    categoryId: "vehicle-maintenance",
    title: "Oil Change",
    slug: "oil-change",
    description: "Full oil and filter change service",
    productType: "service",
    priceAmount: 25.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ duration: "30 min", oil: "synthetic blend" }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 180,
    updatedAt: now - 86400 * 10,
  },
  {
    id: "prod-auto-tire",
    businessId: "biz-auto-repair",
    categoryId: "vehicle-maintenance",
    title: "Tire Replacement",
    slug: "tire-replacement",
    description: "Quality tire replacement and balancing",
    productType: "product",
    priceAmount: 80.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ brand: "Michelin", size: "185/65R15" }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 170,
    updatedAt: now - 86400 * 15,
  },

  // ===== Supermercado Matavia (biz-supermarket-matavia) =====
  {
    id: "prod-matavia-rice-5kg",
    businessId: "biz-supermarket-matavia",
    categoryId: "groceries",
    title: "Premium Rice 5kg",
    slug: "premium-rice-5kg",
    description: "High quality local rice, 5kg bag",
    productType: "product",
    priceAmount: 12.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ weight: "5kg", origin: "Timor-Leste", type: "premium" }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 500,
    updatedAt: now - 86400 * 5,
  },
  {
    id: "prod-matavia-cooking-oil",
    businessId: "biz-supermarket-matavia",
    categoryId: "groceries",
    title: "Cooking Oil 2L",
    slug: "cooking-oil-2l",
    description: "Palm cooking oil, 2 liters",
    productType: "product",
    priceAmount: 5.50,
    priceUnit: "USD",
    specifications: JSON.stringify({ volume: "2L", type: "palm oil" }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 480,
    updatedAt: now - 86400 * 10,
  },

  // ===== Timor Souvenir Shop (biz-toko-souvenir) =====
  {
    id: "prod-souvenir-tais",
    businessId: "biz-toko-souvenir",
    categoryId: "handicrafts",
    title: "Traditional Tais Cloth",
    slug: "traditional-tais-cloth",
    description: "Hand-woven authentic Timorese textile",
    productType: "product",
    priceAmount: 85.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ size: "1m x 2m", material: "cotton", origin: "Aileu" }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 350,
    updatedAt: now - 86400 * 15,
  },
  {
    id: "prod-souvenir-wood-carving",
    businessId: "biz-toko-souvenir",
    categoryId: "handicrafts",
    title: "Wooden carved statue",
    slug: "wooden-carved-statue",
    description: "Traditional Timorese wood carving",
    productType: "product",
    priceAmount: 45.00,
    priceUnit: "USD",
    specifications: JSON.stringify({ height: "30cm", wood: "sandelwood", style: "traditional" }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 340,
    updatedAt: now - 86400 * 20,
  },

  // ===== Banca Timor (biz-bancatimu) =====
  {
    id: "prod-banca-micro-loan",
    businessId: "biz-bancatimu",
    categoryId: "financial-services",
    title: "Micro Business Loan",
    slug: "micro-business-loan",
    description: "Small business financing up to $5,000",
    productType: "service",
    priceAmount: null,
    priceUnit: null,
    specifications: JSON.stringify({ minAmount: 500, maxAmount: 5000, term: "6-24 months", rate: "12% annual" }),
    images: JSON.stringify([]),
    featured: 1,
    active: 1,
    sortOrder: 1,
    createdAt: now - 86400 * 400,
    updatedAt: now - 86400 * 30,
  },
  {
    id: "prod-banca-savings",
    businessId: "biz-bancatimu",
    categoryId: "financial-services",
    title: "Savings Account",
    slug: "savings-account",
    description: "Basic savings account with competitive interest",
    productType: "service",
    priceAmount: null,
    priceUnit: null,
    specifications: JSON.stringify({ minBalance: 10, interestRate: "3% annually", features: ["ATM card", "mobile banking"] }),
    images: JSON.stringify([]),
    featured: 0,
    active: 1,
    sortOrder: 2,
    createdAt: now - 86400 * 380,
    updatedAt: now - 86400 * 25,
  },
];

export default products;