/**
 * Public Sectors Seed Data
 * TimorUp (2026-05-21)
 *
 * 10 realistic Timor-Leste government entities
 */

const now = Math.floor(Date.now() / 1000);

export const publicSectors = [
  // ===== Government Ministries =====
  {
    id: "gov-ministerio-financas",
    title: "Ministry of Finance",
    slug: "ministry-of-finance-tl",
    ownerId: "gov-admin-1",
    categoryId: "ministries",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Servico",
    contactNumber: "77001000",
    countryCode: "+670",
    yearOfEstablishment: 2002,
    email: "info@mof.gov.tl",
    address: "Palacio do Governo, Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "Mon-Fri: 8:30AM-5PM",
    aboutUs: "Responsible for national budget, treasury, tax policy, and financial regulation.",
    tags: "government,finance,budget,tax",
    likes: 345,
    saves: 89,
    views: 4560,
    registrationUrl: "https://www.gov.tl/mof",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "MinisterioFinancasTL" }),
    governmentData: JSON.stringify({
      department: "Ministry",
      serviceTypes: ["Tax Registration", "Business Licensing", "Budget Information"],
      jurisdiction: "National",
    }),
    createdAt: now - 86400 * 1500,
    updatedAt: now - 86400 * 30,
  },
  {
    id: "gov-ministerio-saude",
    title: "Ministry of Health",
    slug: "ministry-of-health-tl",
    ownerId: "gov-admin-2",
    categoryId: "ministries",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Geral",
    contactNumber: "77002000",
    countryCode: "+670",
    yearOfEstablishment: 2002,
    email: "contact@ms.gov.tl",
    address: "Palacio do Governo, Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "Mon-Fri: 8AM-5PM",
    aboutUs: "Overseeing public health services, hospitals, and health policy across Timor-Leste.",
    tags: "government,health,medical,public services",
    likes: 567,
    saves: 234,
    views: 6780,
    registrationUrl: "https://www.gov.tl/ms",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "MinisterioSaudeTL" }),
    governmentData: JSON.stringify({
      department: "Ministry",
      serviceTypes: ["Health Services", "Vaccination Programs", "Hospital Information"],
      jurisdiction: "National",
    }),
    createdAt: now - 86400 * 1450,
    updatedAt: now - 86400 * 15,
  },
  {
    id: "gov-ministerio-educacao",
    title: "Ministry of Education",
    slug: "ministry-of-education-tl",
    ownerId: "gov-admin-3",
    categoryId: "ministries",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Geral",
    contactNumber: "77003000",
    countryCode: "+670",
    yearOfEstablishment: 2002,
    email: "info@me.gov.tl",
    address: "Palacio do Governo, Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "Mon-Fri: 8AM-5PM",
    aboutUs: "Managing national education system, schools, curriculum, and teacher training programs.",
    tags: "government,education,schools,curriculum",
    likes: 489,
    saves: 178,
    views: 5890,
    registrationUrl: "https://www.gov.tl/me",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "MinisterioEducacaoTL" }),
    governmentData: JSON.stringify({
      department: "Ministry",
      serviceTypes: ["School Registration", "Scholarships", "Curriculum Information"],
      jurisdiction: "National",
    }),
    createdAt: now - 86400 * 1400,
    updatedAt: now - 86400 * 20,
  },

  // ===== Police & Security =====
  {
    id: "gov-pntl",
    title: "National Police Timor-Leste (PNTL)",
    slug: "pntl-timor-leste",
    ownerId: "gov-admin-4",
    categoryId: "police",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Estasaun Central",
    contactNumber: "77003333",
    countryCode: "+670",
    yearOfEstablishment: 2000,
    email: "pntl.gov.tl@gmail.com",
    address: "Comoro, Dili",
    locationLat: -8.5456,
    locationLng: 125.5578,
    openingHours: "24/7",
    aboutUs: "Timor-Leste national police force providing law enforcement and public safety services.",
    tags: "police,security,law enforcement,emergency",
    likes: 678,
    saves: 156,
    views: 8900,
    registrationUrl: "https://www.pntl.gov.tl",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "PNTL Timor" }),
    governmentData: JSON.stringify({
      department: "Security",
      serviceTypes: ["Crime Reporting", "Emergency Response", "Traffic Management"],
      jurisdiction: "National",
    }),
    createdAt: now - 86400 * 1600,
    updatedAt: now - 86400 * 10,
  },
  {
    id: "gov-defesa-civil",
    title: "Civil Protection Service",
    slug: "civil-protection-tl",
    ownerId: "gov-admin-5",
    categoryId: "emergency",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Centro Coordenacao",
    contactNumber: "77003334",
    countryCode: "+670",
    yearOfEstablishment: 2008,
    email: "protecao.civil.gov.tl@gmail.com",
    address: "Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "24/7",
    aboutUs: "Managing disaster response, emergency coordination, and civil protection services.",
    tags: "emergency,disaster response,civil protection,safety",
    likes: 234,
    saves: 89,
    views: 3450,
    registrationUrl: null,
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "ProtecaoCivilTL" }),
    governmentData: JSON.stringify({
      department: "Emergency Services",
      serviceTypes: ["Disaster Response", "Emergency Coordination", "Evacuation"],
      jurisdiction: "National",
    }),
    createdAt: now - 86400 * 1100,
    updatedAt: now - 86400 * 25,
  },

  // ===== Immigration & Documentation =====
  {
    id: "gov-migracao",
    title: "Directorate of Migration",
    slug: "migration-directorate-tl",
    ownerId: "gov-admin-6",
    categoryId: "immigration",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Recepcao",
    contactNumber: "77003335",
    countryCode: "+670",
    yearOfEstablishment: 2002,
    email: "migracao@gov.tl",
    address: "Avenida dos Direitos Humanos, Dili",
    locationLat: -8.5612,
    locationLng: 125.5634,
    openingHours: "Mon-Fri: 8AM-4PM",
    aboutUs: "Managing passport issuance, visa applications, and immigration services.",
    tags: "immigration,passport,visa,documentation",
    likes: 456,
    saves: 134,
    views: 5670,
    registrationUrl: "https://www.gov.tl/migracao",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({}),
    governmentData: JSON.stringify({
      department: "Immigration",
      serviceTypes: ["Passport", "Visa", "Work Permit", "Residency"],
      jurisdiction: "National",
    }),
    createdAt: now - 86400 * 1300,
    updatedAt: now - 86400 * 18,
  },

  // ===== Justice & Legal =====
  {
    id: "gov-ministerio-justica",
    title: "Ministry of Justice",
    slug: "ministry-of-justice-tl",
    ownerId: "gov-admin-7",
    categoryId: "justice",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Geral",
    contactNumber: "77004000",
    countryCode: "+670",
    yearOfEstablishment: 2002,
    email: "info@mj.gov.tl",
    address: "Palacio do Governo, Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "Mon-Fri: 8:30AM-5PM",
    aboutUs: "Responsible for legal affairs, prison services, land and property registration.",
    tags: "government,justice,legal,registry",
    likes: 345,
    saves: 98,
    views: 4230,
    registrationUrl: "https://www.gov.tl/mj",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "MinisterioJusticaTL" }),
    governmentData: JSON.stringify({
      department: "Ministry",
      serviceTypes: ["Land Registry", "Company Registration", "Notary Services"],
      jurisdiction: "National",
    }),
    createdAt: now - 86400 * 1350,
    updatedAt: now - 86400 * 22,
  },

  // ===== Taxes & Revenue =====
  {
    id: "gov-servico-receita",
    title: "Tax and Revenue Service",
    slug: "tax-revenue-service-tl",
    ownerId: "gov-admin-8",
    categoryId: "tax",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Atendimento",
    contactNumber: "77005555",
    countryCode: "+670",
    yearOfEstablishment: 2003,
    email: "contact@srt.gov.tl",
    address: "Edificio Financeiro, Dili",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "Mon-Fri: 8AM-4PM",
    aboutUs: "Collecting taxes, managing customs, and revenue enforcement for Timor-Leste.",
    tags: "government,tax,customs,revenue",
    likes: 289,
    saves: 67,
    views: 3890,
    registrationUrl: "https://www.gov.tl/srt",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({}),
    governmentData: JSON.stringify({
      department: "Revenue",
      serviceTypes: ["Income Tax", "VAT", "Customs", "Excise"],
      jurisdiction: "National",
    }),
    createdAt: now - 86400 * 1200,
    updatedAt: now - 86400 * 28,
  },

  // ===== Employment & Labor =====
  {
    id: "gov-servico-emprego",
    title: "National Employment Service",
    slug: "national-employment-service-tl",
    ownerId: "gov-admin-9",
    categoryId: "employment",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Centro Emprego",
    contactNumber: "77006666",
    countryCode: "+670",
    yearOfEstablishment: 2010,
    email: "emprego@gov.tl",
    address: "Lacar Lecidere, Dili",
    locationLat: -8.5590,
    locationLng: 125.5620,
    openingHours: "Mon-Fri: 8AM-4PM",
    aboutUs: "Job placement services, vocational training, and labor market information.",
    tags: "government,employment,jobs,training,labor",
    likes: 456,
    saves: 189,
    views: 5230,
    registrationUrl: "https://www.gov.tl/employment",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "Emprego Timor" }),
    governmentData: JSON.stringify({
      department: "Labor",
      serviceTypes: ["Job Search", "Training", "Career Counseling"],
      jurisdiction: "National",
    }),
    createdAt: now - 86400 * 950,
    updatedAt: now - 86400 * 15,
  },

  // ===== Municipal Services =====
  {
    id: "gov-camara-municipal-dili",
    title: "Dili Municipal Authority",
    slug: "dili-municipal-authority",
    ownerId: "gov-admin-10",
    categoryId: "municipal",
    status: "published",
    bannerImageId: null,
    profileImageId: null,
    contactName: "Gabinete",
    contactNumber: "77007777",
    countryCode: "+670",
    yearOfEstablishment: 2004,
    email: "cmdili@gov.tl",
    address: "Dili Municipal Building",
    locationLat: -8.5569,
    locationLng: 125.5603,
    openingHours: "Mon-Fri: 8AM-5PM",
    aboutUs: "Managing municipal services for Dili: waste collection, roads, permits, and local administration.",
    tags: "government,municipal,dili,local government,public services",
    likes: 567,
    saves: 234,
    views: 6890,
    registrationUrl: "https://www.gov.tl/dili",
    verifiedBadge: 1,
    socialLinks: JSON.stringify({ facebook: "CamaraDili" }),
    governmentData: JSON.stringify({
      department: "Municipal",
      serviceTypes: ["Permits", "Waste Collection", "Road Maintenance", "Local Events"],
      jurisdiction: "Dili Municipality",
    }),
    createdAt: now - 86400 * 1100,
    updatedAt: now - 86400 * 12,
  },
];

export default publicSectors;