-- Businesses Seed Data (18 entries)
-- TimorUp 2026-05-21

-- 1. Café Timor
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-cafe-timor', 'Café Timor', 'cafe-timor', 'owner-1', 'cafes', 'published', 'João Silva', '77001234', '+670', 'info@cafetimor.tl', 'Avenida de Portugal, Dili', -8.5569, 125.5603, 'Mon-Fri: 7AM-10PM, Sat-Sun: 8AM-11PM', 'Café Timor serves the finest Timor-Leste coffee since 2010. Cozy atmosphere for meetings, study sessions, or relaxing with friends.', 'coffee,cafe,wifi,meeting place', 156, 42, 1250, 1, '{"instagram": "@cafetimor", "facebook": "cafetimortl"}', 'Food & Dining', 1700000000, 1750000000);

-- 2. Warung Nazar
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-warung-nazar', 'Warung Nazar', 'warung-nazar', 'owner-2', 'restaurants', 'published', 'Nazar Santos', '77002345', '+670', 'nazarwarung@gmail.com', 'Comoro Road, Dili', -8.5456, 125.5578, 'Daily: 6AM-9PM', 'Traditional Timorese home-style cooking. Fresh local ingredients daily.', 'timorese,local food,home cooking', 89, 23, 678, 0, '{}', 'Food & Dining', 1700000000, 1750000000);

-- 3. Burger King Timor
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-burger-king-dili', 'Burger King Timor', 'burger-king-dili', 'owner-3', 'fast-food', 'published', 'Maria Belo', '77003456', '+670', 'dili@burgerking.tl', 'Beach Road, Dili', -8.4833, 125.5856, 'Daily: 10AM-10PM', 'International fast food chain offering quality burgers and meals.', 'fast food,burger,international', 234, 56, 2340, 1, '{"instagram": "@bkdili"}', 'Food & Dining', 1700000000, 1750000000);

-- 4. Hotel Timor
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-hotel-timor', 'Hotel Timor', 'hotel-timor', 'owner-4', 'hotels', 'published', 'Maria Reis', '77005678', '+670', 'reservations@hoteltimor.tl', 'Beach Road, Dili', -8.4833, 125.5856, '24/7', 'Luxury accommodation with stunning ocean views. Swimming pool, restaurant, and conference facilities.', 'hotel,luxury,pool,ocean view', 289, 78, 3420, 1, '{"instagram": "@hoteltimorl", "facebook": "HotelTimorTL"}', 'Accommodation', 1700000000, 1750000000);

-- 5. Guesthouse Santa Cruz
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-guesthouse-santa', 'Guesthouse Santa Cruz', 'guesthouse-santa-cruz', 'owner-5', 'guesthouses', 'published', 'Francisco Soares', '77006789', '+670', 'santacruzgh@gmail.com', 'Santa Cruz Beach, Dili', -8.4678, 125.5689, 'Check-in: 2PM, Check-out: 11AM', 'Clean, affordable rooms steps from the beach. Perfect for budget travelers.', 'guesthouse,budget,beach,near airport', 67, 34, 890, 0, '{}', 'Accommodation', 1700000000, 1750000000);

-- 6. Timor Tech Solutions
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-timor-tech', 'Timor Tech Solutions', 'timor-tech-solutions', 'owner-6', 'software', 'published', 'Carlos Almeida', '77009999', '+670', 'carlos@timortech.tl', 'Trade Tower, Level 3, Dili', -8.5569, 125.5603, 'Mon-Fri: 8AM-5PM', 'IT consulting, web development, and tech support for businesses.', 'it,consulting,web development,tech support', 87, 23, 890, 1, '{"linkedin": "timor-tech"}', 'Technology', 1700000000, 1750000000);

-- 7. Phone World Timor
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-phone-world', 'Phone World Timor', 'phone-world-timor', 'owner-7', 'phone-shops', 'published', 'Rui Fernandes', '77001234', '+670', 'phoneworld.tl@gmail.com', 'Lacar Lecidere, Dili', -8.5590, 125.5620, 'Daily: 8AM-8PM', 'Latest smartphones, SIM cards, top-ups, and professional repair services.', 'phones,accessories,repair,sim card', 145, 38, 1560, 1, '{"instagram": "@phoneworldtl"}', 'Retail', 1700000000, 1750000000);

-- 8. Timor Dental Clinic
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-dental-clinic', 'Timor Dental Clinic', 'timor-dental-clinic', 'owner-8', 'dental', 'published', 'Dr. Pedro Santos', '77007890', '+670', 'info@timordental.tl', 'Main Street, Dili', -8.5569, 125.5603, 'Mon-Sat: 8AM-5PM', 'Comprehensive dental care: check-ups, cleanings, fillings, and cosmetic dentistry.', 'dental,health,medical,clinic', 67, 18, 789, 1, '{}', 'Healthcare', 1700000000, 1750000000);

-- 9. Pharma Plus Dili
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-pharma-plus', 'Pharma Plus Dili', 'pharma-plus-dili', 'owner-9', 'pharmacies', 'published', 'Ana Lima', '77004567', '+670', 'pharmaplus.tl@gmail.com', 'Bidau Lecidere, Dili', -8.5489, 125.5645, 'Daily: 7AM-10PM', 'Wide selection of medicines, health products, and cosmetics. Professional advice available.', 'pharmacy,medicine,health,cosmetics', 98, 27, 1120, 1, '{"facebook": "PharmaPlusDili"}', 'Healthcare', 1700000000, 1750000000);

-- 10. Fitness First Timor
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-fit-gym', 'Fitness First Timor', 'fitness-first-timor', 'owner-10', 'gyms', 'published', 'Paulo Gusmão', '77005678', '+670', 'info@fitnessfirst.tl', 'Camboa, Dili', -8.5345, 125.5523, 'Daily: 5AM-10PM', 'Modern equipment, personal trainers, and group classes. Yoga, Zumba, and weight training.', 'gym,fitness,personal training,yoga', 134, 45, 1670, 0, '{"instagram": "@fitnessfirsttl"}', 'Health & Fitness', 1700000000, 1750000000);

-- 11. English Learning Center Timor
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-english-center', 'English Learning Center Timor', 'english-learning-center', 'owner-11', 'language-centers', 'published', 'Susan Brown', '77009876', '+670', 'info@englishtimor.tl', 'Fatuhada, Dili', -8.5623, 125.5698, 'Mon-Fri: 8AM-7PM, Sat: 9AM-1PM', 'IELTS and TOEIC preparation, conversational English, business English courses.', 'english,language,ielts,education', 78, 32, 920, 1, '{"facebook": "EnglishTimor"}', 'Education', 1700000000, 1750000000);

-- 12. Salon Maria
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-salon-maria', 'Salon Maria', 'salon-maria', 'owner-12', 'salons', 'published', 'Maria Oliveira', '77002345', '+670', 'mariasalon.tl@gmail.com', 'Lacar Lecidere, Dili', -8.5590, 125.5620, 'Tue-Sat: 9AM-6PM', 'Professional hair cutting, coloring, and styling. Bridal makeup services available.', 'salon,hair,beauty,bridal', 56, 19, 678, 0, '{"instagram": "@salonmariadili"}', 'Beauty & Personal Care', 1700000000, 1750000000);

-- 13. Timor Auto Repair
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-auto-repair', 'Timor Auto Repair', 'timor-auto-repair', 'owner-13', 'repair-shops', 'published', 'Joaquim Santos', '77007890', '+670', 'auto.timor@gmail.com', 'Hera Industrial Zone, Dili', -8.5234, 125.5432, 'Mon-Sat: 8AM-5PM', 'Engine repair, oil change, tire service, and full vehicle maintenance.', 'auto,repair,mechanic,maintenance', 45, 12, 456, 0, '{}', 'Automotive', 1700000000, 1750000000);

-- 14. Shell Comoro
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-shell-station', 'Shell Comoro', 'shell-comoro', 'owner-14', 'gas-stations', 'published', 'Manager', '77001111', '+670', '', 'Comoro Road, Dili', -8.5456, 125.5578, '24/7', 'Shell fuel station with convenience store. Air, water, and tire inflation available.', 'fuel,gas,convenience,24/7', 89, 8, 2340, 1, '{}', 'Automotive', 1700000000, 1750000000);

-- 15. Supermercado Matavia
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-supermarket-matavia', 'Supermercado Matavia', 'supermercado-matavia', 'owner-15', 'supermarkets', 'published', 'Manuel da Costa', '77009999', '+670', 'matavia.supermarket@gmail.com', 'Matavia, Dili', -8.5123, 125.5512, 'Daily: 7AM-9PM', 'Wide selection of local and imported products. Fresh produce, household items, and beverages.', 'supermarket,grocery,imported goods', 178, 34, 2890, 1, '{"facebook": "SupermercadoMatavia"}', 'Retail', 1700000000, 1750000000);

-- 16. Timor Souvenir Shop
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-toko-souvenir', 'Timor Souvenir Shop', 'timor-souvenir-shop', 'owner-16', 'local-crafts', 'published', 'Rosa Fernandes', '77003456', '+670', 'timorsouvenir@gmail.com', 'Arte Moris, Dili', -8.4789, 125.5890, 'Daily: 9AM-5PM', 'Hand-woven textiles, carved wood, and traditional Timorese artifacts.', 'souvenir,handicraft,traditional,textiles', 123, 67, 1890, 1, '{"instagram": "@timorsouvenir"}', 'Retail', 1700000000, 1750000000);

-- 17. Banca Timor
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-bancatimu', 'Banca Timor', 'banca-timor', 'owner-17', 'banks', 'published', 'Director', '77001122', '+670', 'info@bancatimu.tl', 'Avenida dos Direitos Humanos, Dili', -8.5612, 125.5634, 'Mon-Fri: 8AM-3PM', 'Microfinance services for small businesses and entrepreneurs. Loans and savings accounts.', 'bank,finance,microfinance,business loan', 67, 23, 789, 1, '{}', 'Finance', 1700000000, 1750000000);

-- 18. Aqua Timor
INSERT INTO businesses (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, verified_badge, social_links, industry, created_at, updated_at) VALUES ('biz-water-timor', 'Aqua Timor', 'aqua-timor', 'owner-18', 'water-supply', 'published', 'Antonio til', '77009988', '+670', 'info@aquatimor.tl', 'Hera Industrial Zone, Dili', -8.5234, 125.5432, 'Mon-Sat: 7AM-6PM', 'Bottled water delivery service and water filter installation.', 'water,bottled,delivery,filter', 45, 18, 567, 0, '{}', 'Utilities', 1700000000, 1750000000);