-- Categories Seed Data
-- TimorUp 2026-05-21

-- Business Categories (56 entries)
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('food-dining', 'Food & Dining', 'food-dining', 'Restaurants, cafés, and food services', 'UtensilsCrossed', NULL, 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('restaurants', 'Restaurants', 'restaurants', 'Full-service restaurants', 'Utensils', 'food-dining', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('cafes', 'Cafés', 'cafes', 'Coffee shops and cafés', 'Coffee', 'food-dining', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('fast-food', 'Fast Food', 'fast-food', 'Fast food chains and outlets', 'Burger', 'food-dining', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('food-stalls', 'Food Stalls', 'food-stalls', 'Street food and local markets', 'Store', 'food-dining', 4, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('timorese-cuisine', 'Timorese Cuisine', 'timorese-cuisine', 'Traditional Timor-Leste cuisine', 'ChefHat', 'food-dining', 5, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('accommodation', 'Accommodation', 'accommodation', 'Hotels, guesthouses, and lodging', 'Bed', NULL, 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('hotels', 'Hotels', 'hotels', 'Hotels and resorts', 'Building', 'accommodation', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('guesthouses', 'Guesthouses', 'guesthouses', 'Guesthouses and B&Bs', 'Home', 'accommodation', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('hostels', 'Hostels', 'hostels', 'Budget hostels', 'Backpack', 'accommodation', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('homestays', 'Homestays', 'homestays', 'Home-stay accommodations', 'Heart', 'accommodation', 4, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('retail-shops', 'Retail & Shops', 'retail-shops', 'Retail stores and shops', 'ShoppingBag', NULL, 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('supermarkets', 'Supermarkets', 'supermarkets', 'Large grocery stores', 'ShoppingCart', 'retail-shops', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('markets', 'Markets', 'markets', 'Traditional markets', 'Store', 'retail-shops', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('convenience-stores', 'Convenience Stores', 'convenience-stores', 'Convenience and minimarts', 'CreditCard', 'retail-shops', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('specialty-shops', 'Specialty Shops', 'specialty-shops', 'Specialized retail', 'Sparkles', 'retail-shops', 4, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('transportation', 'Transportation', 'transportation', 'Transport and travel services', 'Car', NULL, 4, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('taxis', 'Taxis', 'taxis', 'Taxi services', 'Taxi', 'transportation', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('car-rentals', 'Car Rentals', 'car-rentals', 'Vehicle rental services', 'Key', 'transportation', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('tours-travel', 'Tours & Travel', 'tours-travel', 'Tour operators and travel agencies', 'Map', 'transportation', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('bus-services', 'Bus Services', 'bus-services', 'Public and private bus services', 'Bus', 'transportation', 4, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('professional-services', 'Professional Services', 'professional-services', 'Professional and business services', 'Briefcase', NULL, 5, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('banks-finance', 'Banks & Finance', 'banks-finance', 'Banks and financial institutions', 'Landmark', 'professional-services', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('legal-services', 'Legal Services', 'legal-services', 'Lawyers and legal firms', 'Scale', 'professional-services', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('accounting', 'Accounting', 'accounting', 'Accounting and bookkeeping', 'Calculator', 'professional-services', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('insurance', 'Insurance', 'insurance', 'Insurance providers', 'Shield', 'professional-services', 4, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('consulting', 'Consulting', 'consulting', 'Business consulting', 'MessageSquare', 'professional-services', 5, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('health-wellness', 'Health & Wellness', 'health-wellness', 'Healthcare and wellness services', 'Heart', NULL, 6, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('clinics', 'Clinics', 'clinics', 'Medical clinics', 'Stethoscope', 'health-wellness', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('pharmacies', 'Pharmacies', 'pharmacies', 'Pharmacies and drugstores', 'Pill', 'health-wellness', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('gyms-fitness', 'Gyms & Fitness', 'gyms-fitness', 'Fitness centers', 'Dumbbell', 'health-wellness', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('spas-massage', 'Spas & Massage', 'spas-massage', 'Spa and massage services', 'Sparkles', 'health-wellness', 4, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('optical-eyewear', 'Optical & Eyewear', 'optical-eyewear', 'Opticians and eyewear', 'Glasses', 'health-wellness', 5, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('dental-services', 'Dental Services', 'dental-services', 'Dental clinics', 'Smile', 'health-wellness', 6, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('education', 'Education', 'education', 'Schools and educational services', 'GraduationCap', NULL, 7, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('schools', 'Schools', 'schools', 'Primary and secondary schools', 'Building2', 'education', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('language-centers', 'Language Centers', 'language-centers', 'Language learning centers', 'Languages', 'education', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('training-centers', 'Training Centers', 'training-centers', 'Vocational training', 'Award', 'education', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('tutoring', 'Tutoring', 'tutoring', 'Private tutoring services', 'BookOpen', 'education', 4, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('construction-trades', 'Construction & Trades', 'construction-trades', 'Construction and home services', 'HardHat', NULL, 8, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('contractors', 'Contractors', 'contractors', 'Building contractors', 'Hammer', 'construction-trades', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('electricians', 'Electricians', 'electricians', 'Electrical services', 'Zap', 'construction-trades', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('plumbers', 'Plumbers', 'plumbers', 'Plumbing services', 'Wrench', 'construction-trades', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('painters', 'Painters', 'painters', 'Painting services', 'Paintbrush', 'construction-trades', 4, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('furniture-makers', 'Furniture Makers', 'furniture-makers', 'Custom furniture', 'Armchair', 'construction-trades', 5, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('entertainment', 'Entertainment', 'entertainment', 'Entertainment and leisure', 'Ticket', NULL, 9, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('bars-clubs', 'Bars & Clubs', 'bars-clubs', 'Bars and nightclubs', 'Wine', 'entertainment', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('cinemas', 'Cinemas', 'cinemas', 'Movie theaters', 'Film', 'entertainment', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('sports-recreation', 'Sports & Recreation', 'sports-recreation', 'Sports venues and activities', 'Trophy', 'entertainment', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('event-venues', 'Event Venues', 'event-venues', 'Event halls and venues', 'Calendar', 'entertainment', 4, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('agriculture', 'Agriculture', 'agriculture', 'Farming and agricultural services', 'Wheat', NULL, 10, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('farms', 'Farms', 'farms', 'Farms and plantations', 'Sprout', 'agriculture', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('agri-markets', 'Agricultural Markets', 'agri-markets', 'Farm produce markets', 'Apple', 'agriculture', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('agri-supplies', 'Agri Supplies', 'agri-supplies', 'Seeds, fertilizers, tools', 'Package', 'agriculture', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('livestock', 'Livestock', 'livestock', 'Livestock sales', 'Rabbit', 'agriculture', 4, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('technology-it', 'Technology & IT', 'technology-it', 'Technology and IT services', 'Laptop', NULL, 11, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('phone-shops', 'Phone Shops', 'phone-shops', 'Mobile phone retailers', 'Smartphone', 'technology-it', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('internet-cafes', 'Internet Cafés', 'internet-cafes', 'Internet and gaming cafés', 'Monitor', 'technology-it', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('repair-services', 'Repair Services', 'repair-services', 'Electronics repair', 'Wrench', 'technology-it', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('software-it', 'Software & IT', 'software-it', 'Software and IT services', 'Code', 'technology-it', 4, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('beauty-personal-care', 'Beauty & Personal Care', 'beauty-personal-care', 'Salons and personal care', 'Scissors', NULL, 12, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('hair-salons', 'Hair Salons', 'hair-salons', 'Hair salons and barbershops', 'Scissors', 'beauty-personal-care', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('beauty-parlors', 'Beauty Parlors', 'beauty-parlors', 'Beauty and nail services', 'Sparkles', 'beauty-personal-care', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('laundries', 'Laundries', 'laundries', 'Laundry and dry cleaning', 'Shirt', 'beauty-personal-care', 3, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('automotive', 'Automotive', 'automotive', 'Vehicle sales and services', 'Car', NULL, 13, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('gas-stations', 'Gas Stations', 'gas-stations', 'Petrol stations', 'Fuel', 'automotive', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('repair-shops', 'Repair Shops', 'repair-shops', 'Vehicle repair', 'Wrench', 'automotive', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('auto-parts', 'Auto Parts', 'auto-parts', 'Car parts and accessories', 'Cog', 'automotive', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('car-dealers', 'Car Dealers', 'car-dealers', 'Vehicle sales', 'Car', 'automotive', 4, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('crafts-souvenirs', 'Crafts & Souvenirs', 'crafts-souvenirs', 'Local crafts and souvenirs', 'Gift', NULL, 14, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('local-crafts', 'Local Crafts', 'local-crafts', 'Traditional Timorese crafts', 'Palette', 'crafts-souvenirs', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('gift-shops', 'Gift Shops', 'gift-shops', 'Gift and souvenir shops', 'Gift', 'crafts-souvenirs', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('jewelry', 'Jewelry', 'jewelry', 'Jewelry shops', 'Gem', 'crafts-souvenirs', 3, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('financial-communication', 'Financial & Communication', 'financial-communication', 'Finance and communications', 'Phone', NULL, 15, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('money-transfer', 'Money Transfer', 'money-transfer', 'Remittance services', 'Send', 'financial-communication', 1, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('telecom-services', 'Telecom Services', 'telecom-services', 'Phone and internet providers', 'Signal', 'financial-communication', 2, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('printing-copy', 'Printing & Copy', 'printing-copy', 'Printing and copying services', 'Printer', 'financial-communication', 3, 1, 1700000000, 1750000000);
INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('photography', 'Photography', 'photography', 'Photo studios', 'Camera', 'financial-communication', 4, 1, 1700000000, 1750000000);

INSERT INTO business_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('water-supply', 'Water Supply', 'water-supply', 'Water delivery and supply', 'Droplets', NULL, 16, 1, 1700000000, 1750000000);

-- Non-Profit Categories
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('healthcare', 'Healthcare', 'healthcare', 'Medical and health services', 'Heart', NULL, 1, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('education', 'Education', 'education', 'Educational programs and schools', 'GraduationCap', NULL, 2, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('environment', 'Environment', 'environment', 'Environmental conservation', 'Leaf', NULL, 3, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('agriculture', 'Agriculture', 'agriculture', 'Farming and food security', 'Wheat', NULL, 4, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('women', 'Women & Gender', 'women', 'Women empowerment and gender equality', 'Users', NULL, 5, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('community', 'Community Development', 'community', 'Community programs and services', 'Users', NULL, 6, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('disability', 'Disability', 'disability', 'Disability services and advocacy', 'Accessibility', NULL, 7, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('social-services', 'Social Services', 'social-services', 'Social welfare and support', 'HandHeart', NULL, 8, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('youth', 'Youth', 'youth', 'Youth development programs', 'User', NULL, 9, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('humanitarian', 'Humanitarian', 'humanitarian', 'Emergency relief and humanitarian aid', 'AlertTriangle', NULL, 10, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('governance', 'Governance & Advocacy', 'governance', 'Governance and policy advocacy', 'Shield', NULL, 11, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('research', 'Research & Development', 'research', 'Research and development programs', 'Microscope', NULL, 12, 1, 1700000000, 1750000000);
INSERT INTO non_profit_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('religious', 'Religious', 'religious', 'Religious and faith-based organizations', 'Church', NULL, 13, 1, 1700000000, 1750000000);

-- Public Sector Categories
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('ministries', 'Government Ministries', 'ministries', 'National government ministries', 'Building', NULL, 1, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('police', 'Police & Security', 'police', 'Law enforcement agencies', 'Shield', NULL, 2, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('emergency', 'Emergency Services', 'emergency', 'Emergency and disaster response', 'AlertTriangle', NULL, 3, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('immigration', 'Immigration & Documentation', 'immigration', 'Passport and visa services', 'FileText', NULL, 4, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('justice', 'Justice & Legal', 'justice', 'Courts and legal services', 'Scale', NULL, 5, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('tax', 'Tax & Revenue', 'tax', 'Tax and customs services', 'Calculator', NULL, 6, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('employment', 'Employment & Labor', 'employment', 'Job and labor services', 'Briefcase', NULL, 7, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('municipal', 'Municipal Services', 'municipal', 'Local government services', 'MapPin', NULL, 8, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('health-dept', 'Health Department', 'health-department', 'Public health services', 'Heart', NULL, 9, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('education-dept', 'Education Department', 'education-department', 'Education administration', 'Book', NULL, 10, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('agriculture-dept', 'Agriculture Department', 'agriculture-department', 'Agricultural services', 'Sprout', NULL, 11, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('transport', 'Transport & Infrastructure', 'transport', 'Transport and infrastructure', 'Car', NULL, 12, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('tourism', 'Tourism Authority', 'tourism', 'Tourism promotion', 'Map', NULL, 13, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('customs', 'Customs Authority', 'customs', 'Customs and border control', 'Package', NULL, 14, 1, 1700000000, 1750000000);
INSERT INTO public_sector_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, created_at, updated_at) VALUES ('elections', 'Elections Commission', 'elections', 'National election services', 'CheckSquare', NULL, 15, 1, 1700000000, 1750000000);

-- Listing Categories (73 entries)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('jobs', 'Jobs', 'jobs', 'Employment opportunities', 'Briefcase', NULL, 1, 1, '{"fields": [{"name": "salary", "label": "Salary", "type": "number"}, {"name": "jobType", "label": "Job Type", "type": "select", "options": ["Full-time", "Part-time", "Contract"]}]}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('teaching', 'Teaching', 'teaching', 'Teaching and education jobs', 'GraduationCap', 'jobs', 1, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('finance', 'Finance & Accounting', 'finance', 'Finance and accounting positions', 'Calculator', 'jobs', 2, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('drivers', 'Drivers & Transport', 'drivers', 'Driver and transport jobs', 'Car', 'jobs', 3, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('hospitality', 'Hospitality', 'hospitality', 'Hotel and restaurant jobs', 'Utensils', 'jobs', 4, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('ngo', 'NGO & Development', 'ngo', 'NGO and development sector jobs', 'Heart', 'jobs', 5, 1, '{}', 1700000000, 1750000000);

INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('vehicles', 'Vehicles', 'vehicles', 'Vehicles for sale', 'Car', NULL, 2, 1, '{"fields": [{"name": "make", "label": "Make", "type": "text"}, {"name": "model", "label": "Model", "type": "text"}, {"name": "year", "label": "Year", "type": "number"}, {"name": "mileage", "label": "Mileage", "type": "number"}, {"name": "fuel", "label": "Fuel Type", "type": "select", "options": ["Petrol", "Diesel", "Electric"]}]}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('cars', 'Cars', 'cars', 'Cars for sale', 'Car', 'vehicles', 1, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('motorcycles', 'Motorcycles', 'motorcycles', 'Motorcycles for sale', 'Bike', 'vehicles', 2, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('vans', 'Vans & Buses', 'vans', 'Vans and buses for sale', 'Bus', 'vehicles', 3, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('trucks', 'Trucks', 'trucks', 'Trucks for sale', 'Truck', 'vehicles', 4, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('other-vehicles', 'Other Vehicles', 'other-vehicles', 'Other types of vehicles', 'CircleDot', 'vehicles', 5, 1, '{}', 1700000000, 1750000000);

INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('property', 'Property', 'property', 'Real estate listings', 'Home', NULL, 3, 1, '{"fields": [{"name": "bedrooms", "label": "Bedrooms", "type": "number"}, {"name": "bathrooms", "label": "Bathrooms", "type": "number"}, {"name": "area", "label": "Area (sqm)", "type": "number"}]}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('apartments', 'Apartments', 'apartments', 'Apartments for rent', 'Building', 'property', 1, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('houses', 'Houses', 'houses', 'Houses for rent', 'Home', 'property', 2, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('land', 'Land', 'land', 'Land for sale or rent', 'Map', 'property', 3, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('commercial', 'Commercial', 'commercial', 'Commercial property', 'Building', 'property', 4, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('industrial', 'Industrial', 'industrial', 'Industrial property', 'Factory', 'property', 5, 1, '{}', 1700000000, 1750000000);

INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('for-sale', 'For Sale', 'for-sale', 'Items for sale', 'ShoppingBag', NULL, 4, 1, '{"fields": [{"name": "condition", "label": "Condition", "type": "select", "options": ["New", "Like New", "Good", "Fair"]}]}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('electronics', 'Electronics', 'electronics', 'Electronic devices', 'Smartphone', 'for-sale', 1, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('furniture', 'Furniture', 'furniture', 'Furniture and home items', 'Armchair', 'for-sale', 2, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('sports', 'Sports & Outdoors', 'sports', 'Sports and outdoor equipment', 'Dumbbell', 'for-sale', 3, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('arts', 'Arts & Collectibles', 'arts', 'Art and collectibles', 'Palette', 'for-sale', 4, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('clothing', 'Clothing & Fashion', 'clothing', 'Clothing and fashion items', 'Shirt', 'for-sale', 5, 1, '{}', 1700000000, 1750000000);

INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('services', 'Services', 'services', 'Professional services', 'Wrench', NULL, 5, 1, '{"fields": [{"name": "serviceType", "label": "Service Type", "type": "text"}]}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('photography', 'Photography', 'photography', 'Photography services', 'Camera', 'services', 1, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('home-repair', 'Home Repair', 'home-repair', 'Home repair services', 'Wrench', 'services', 2, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('tutoring', 'Tutoring', 'tutoring', 'Tutoring services', 'BookOpen', 'services', 3, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('cleaning', 'Cleaning', 'cleaning', 'Cleaning services', 'Sparkles', 'services', 4, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('moving', 'Moving & Delivery', 'moving', 'Moving and delivery services', 'Truck', 'services', 5, 1, '{}', 1700000000, 1750000000);

INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('community', 'Community', 'community', 'Community and events', 'Users', NULL, 6, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('events', 'Events & Classes', 'events', 'Events and classes', 'Calendar', 'community', 1, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('announcements', 'Announcements', 'announcements', 'Community announcements', 'Megaphone', 'community', 2, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('volunteer', 'Volunteer', 'volunteer', 'Volunteer opportunities', 'Heart', 'community', 3, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('lost-found', 'Lost & Found', 'lost-found', 'Lost and found items', 'Search', 'community', 4, 1, '{}', 1700000000, 1750000000);

INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('agriculture', 'Agriculture', 'agriculture', 'Agriculture and farming', 'Sprout', NULL, 7, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('farm-equipment', 'Farm Equipment', 'farm-equipment', 'Farm equipment for sale', 'Tractor', 'agriculture', 1, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('livestock', 'Livestock', 'livestock', 'Livestock for sale', 'Rabbit', 'agriculture', 2, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('seeds-plants', 'Seeds & Plants', 'seeds-plants', 'Seeds and plants for sale', 'Sprout', 'agriculture', 3, 1, '{}', 1700000000, 1750000000);
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields, created_at, updated_at) VALUES ('produce', 'Fresh Produce', 'produce', 'Fresh produce for sale', 'Apple', 'agriculture', 4, 1, '{}', 1700000000, 1750000000);