-- Listings Seed Data (25 entries)
-- TimorUp 2026-05-21

-- Jobs (5)
INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-job-teacher-1', 'English Teacher Wanted - International School', 'english-teacher-international-school', 'user-1', 'teaching', 'published', 'International school in Dili seeking qualified English teacher for primary grades. Must have teaching certification and 2+ years experience.', 1200.00, 'USD/month', NULL, 'Dili', -8.5569, 125.5603, 'Maria Santos', '77001111', '+670', 'teach@dili-school.tl', 'english,teacher,international,school', 45, 23, 567, 1750000000, NULL, 0, NULL, '{"jobType": "full-time", "experience": "2+ years", "qualification": "TEFL/CELTA"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-job-accountant-1', 'Accountant needed for Audit Firm', 'accountant-audit-firm-dili', 'user-2', 'finance', 'published', 'Growing audit firm seeks experienced accountant. Responsibilities include bookkeeping, tax preparation, and client liaison.', 800.00, 'USD/month', NULL, 'Dili', -8.5569, 125.5603, 'Carlos til', '77002222', '+670', 'careers@audit-tl.com', 'accountant,audit,finance,bookkeeping', 34, 18, 345, 1750000000, NULL, 0, NULL, '{"jobType": "full-time", "experience": "3+ years", "qualification": "ACCA/CPA preferred"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-job-driver-1', 'Driver Needed - Logistics Company', 'driver-logistics-company', 'user-3', 'drivers', 'published', 'Reliable driver needed for delivery truck. Must have valid Timor-Leste license and clean driving record.', 500.00, 'USD/month', NULL, 'Dili', -8.5569, 125.5603, 'Joaquim til', '77003333', '+670', 'driver@logistics.tl', 'driver,logistics,delivery,truck', 67, 12, 890, 1750000000, NULL, 1, 1750000000, '{"jobType": "full-time", "license": "Class B", "experience": "2+ years"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-job-chef-1', 'Head Chef - Beach Resort Restaurant', 'head-chef-beach-resort', 'user-4', 'hospitality', 'published', 'Beach resort restaurant seeking experienced head chef. International cuisine, live kitchen, competitive salary plus accommodation.', 1500.00, 'USD/month', NULL, 'Dili', -8.4789, 125.5890, 'Ana til', '77004444', '+670', 'jobs@beachresort.tl', 'chef,restaurant,beach resort,hospitality', 89, 45, 1230, 1750000000, NULL, 1, 1750000000, '{"jobType": "full-time", "accommodation": true, "experience": "5+ years"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-job-ngo-1', 'Project Coordinator - NGO', 'project-coordinator-ngo-dili', 'user-5', 'ngo', 'published', 'International NGO seeks project coordinator for community development programs. Master degree preferred, 4+ years relevant experience.', 1800.00, 'USD/month', NULL, 'Dili', -8.5569, 125.5603, 'HR til', '77005555', '+670', 'recruitment@ngotl.org', 'ngo,project coordinator,development,community', 56, 34, 678, 1750000000, NULL, 0, NULL, '{"jobType": "contract", "degree": "Master preferred", "experience": "4+ years"}', 1700000000, 1750000000);

-- Vehicles (5)
INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-vehicle-toyota-1', 'Toyota Hilux 2022 - Low Mileage', 'toyota-hilux-2022-dili', 'user-6', 'cars', 'published', 'Excellent condition Toyota Hilux 4x4, 2022 model. Only 45,000km. Full service history. Automatic transmission, diesel engine.', 28000.00, 'USD', 'excellent', 'Dili', -8.5569, 125.5603, 'Rui til', '77006666', '+670', 'toyota.sale@gmail.com', 'toyota,hilux,4x4,truck,diesel', 123, 56, 2340, 1750000000, NULL, 1, 1750000000, '{"make": "Toyota", "model": "Hilux", "year": 2022, "mileage": 45000, "fuel": "diesel", "transmission": "automatic"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-vehicle-honda-1', 'Honda PCX 150 Scooter - Great Deal', 'honda-pcx-150-scooter', 'user-7', 'motorcycles', 'published', 'Reliable Honda PCX 150 scooter, perfect for Dili traffic. Low fuel consumption, automatic, great condition.', 3500.00, 'USD', 'good', 'Dili', -8.5569, 125.5603, 'Paulo til', '77007777', '+670', 'scooter.sale.tl@gmail.com', 'honda,pcx,scooter,motorcycle,automatic', 78, 34, 1560, 1750000000, NULL, 0, NULL, '{"make": "Honda", "model": "PCX 150", "year": 2021, "mileage": 12000, "fuel": "petrol"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-vehicle-landcruiser-1', 'Toyota Land Cruiser 200 Series', 'toyota-land-cruiser-200-dili', 'user-8', 'cars', 'published', 'Premium Land Cruiser 200 series, V8 diesel. Top model with leather seats, sunroof, and full option package.', 45000.00, 'USD', 'excellent', 'Dili', -8.5569, 125.5603, 'Luis til', '77008888', '+670', 'landcruiser.sale@gmail.com', 'toyota,land cruiser,suv,premium,v8', 234, 89, 3450, 1750000000, NULL, 1, 1750000000, '{"make": "Toyota", "model": "Land Cruiser 200", "year": 2021, "mileage": 35000, "fuel": "diesel"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-vehicle-van-1', 'Toyota HiAce Van - 12 Seater', 'toyota-hiace-van-12-seater', 'user-9', 'vans', 'published', 'Spacious Toyota HiAce van, 12 seats. Perfect for shuttle service or large family. Diesel, manual transmission.', 18000.00, 'USD', 'good', 'Dili', -8.5569, 125.5603, 'Manuel til', '77009999', '+670', 'vanforsale.tl@gmail.com', 'toyota,hiace,van,shuttle,12 seater', 67, 23, 1230, 1750000000, NULL, 0, NULL, '{"make": "Toyota", "model": "HiAce", "year": 2019, "mileage": 78000, "fuel": "diesel", "seats": 12}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-vehicle-utv-1', 'Yamaha Quad Bike - Off Road', 'yamaha-quad-bike-offroad', 'user-10', 'other-vehicles', 'published', 'Yamaha YFZ450 quad bike, great for farm or off-road adventures. Recently serviced, new tires.', 4500.00, 'USD', 'good', 'Aileu', -8.7306, 125.4044, 'Joao til', '77001010', '+670', 'quadbike.tl@gmail.com', 'yamaha,quad,bike,offroad,farm', 34, 12, 567, 1750000000, NULL, 0, NULL, '{"make": "Yamaha", "model": "YFZ450", "year": 2020, "condition": "off-road"}', 1700000000, 1750000000);

-- Property (5)
INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-property-apartment-1', 'Modern 2BR Apartment - Near Beach', 'modern-2br-apartment-near-beach', 'user-11', 'apartments', 'published', 'Fully furnished 2 bedroom apartment with ocean view. AC in all rooms, hot water, fully equipped kitchen. Security 24/7.', 600.00, 'USD/month', NULL, 'Beach Road, Dili', -8.4833, 125.5856, 'Maria til', '77001212', '+670', 'apartment.rent.tl@gmail.com', 'apartment,2 bedroom,furnished,beach,near', 89, 45, 2340, 1750000000, NULL, 1, 1750000000, '{"bedrooms": 2, "bathrooms": 1, "furnished": true, "parking": true}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-property-house-1', '3 Bedroom House - Gic facility', '3-bedroom-house-gic', 'user-12', 'houses', 'published', 'Spacious 3 bedroom house in quiet Gic area. Large garden, garage, fully fenced. Water tank and generator included.', 800.00, 'USD/month', NULL, 'Gic, Dili', -8.5345, 125.5523, 'Antonio til', '77001313', '+670', 'house.rent.tl@gmail.com', 'house,3 bedroom,garden,garage,fenced', 67, 34, 1780, 1750000000, NULL, 0, NULL, '{"bedrooms": 3, "bathrooms": 2, "furnished": false, "landSize": "500m2"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-property-land-1', 'Commercial Land - Main Road', 'commercial-land-main-road-dili', 'user-13', 'land', 'published', 'Prime commercial land on main road. 1000m2, level terrain, all utilities available. Perfect for shop or office.', 150000.00, 'USD', NULL, 'Comoro Road, Dili', -8.5456, 125.5578, 'Fernanda til', '77001414', '+670', 'land.sale.tl@gmail.com', 'land,commercial,main road,1000m2,prime', 134, 56, 2890, 1750000000, NULL, 1, 1750000000, '{"landSize": "1000m2", "zoning": "commercial", "utilities": ["electricity", "water", "road access"]}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-property-office-1', 'Office Space - Trade Tower', 'office-space-trade-tower-dili', 'user-14', 'commercial', 'published', 'Modern office space in Trade Tower building. 80m2, lift access, parking included. Long term lease available.', 1200.00, 'USD/month', NULL, 'Trade Tower, Dili', -8.5569, 125.5603, 'Carlos til', '77001515', '+670', 'office.rent.tl@gmail.com', 'office,commercial,trade tower,modern,80m2', 56, 23, 1230, 1750000000, NULL, 0, NULL, '{"size": "80m2", "parking": true, "lift": true}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-property-warehouse-1', 'Warehouse - Hera Industrial Zone', 'warehouse-hera-industrial-zone', 'user-15', 'industrial', 'published', 'Large warehouse in Hera Industrial Zone. 500m2, high ceiling, loading dock. Ideal for storage or light manufacturing.', 2500.00, 'USD/month', NULL, 'Hera Industrial Zone, Dili', -8.5234, 125.5432, 'Pedro til', '77001616', '+670', 'warehouse.rent.tl@gmail.com', 'warehouse,industrial,hera,storage,500m2', 45, 18, 890, 1750000000, NULL, 0, NULL, '{"size": "500m2", "ceilingHeight": "6m", "loadingDock": true}', 1700000000, 1750000000);

-- For Sale (5)
INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-sale-fridge-1', 'Samsung Double Door Fridge - New', 'samsung-double-door-fridge-dili', 'user-16', 'electronics', 'published', 'Brand new Samsung double door refrigerator. Inverter technology, energy efficient. Full warranty included.', 850.00, 'USD', 'new', 'Dili', -8.5569, 125.5603, 'Ana til', '77001717', '+670', 'electronics.sale.tl@gmail.com', 'samsung,fridge,refrigerator,electronics,new', 34, 12, 567, 1750000000, NULL, 0, NULL, '{"brand": "Samsung", "type": "double door", "warranty": "2 years"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-sale-sofa-1', 'L-Shape Sofa Set - Like New', 'l-shape-sofa-set-like-new', 'user-17', 'furniture', 'published', 'Comfortable L-shape sofa set, gray color. Only 6 months old, like new condition. Moving sale.', 450.00, 'USD', 'like-new', 'Lacar Lecidere, Dili', -8.5590, 125.5620, 'Joaquim til', '77001818', '+670', 'furniture.sale.tl@gmail.com', 'sofa,furniture,l-shape,gray,like new', 23, 8, 345, 1750000000, NULL, 0, NULL, '{"type": "L-shape", "color": "gray", "material": "fabric"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-sale-bike-1', 'Mountain Bike - Trek Marlin 7', 'trek-marlin-7-mountain-bike', 'user-18', 'sports', 'published', 'Trek Marlin 7 mountain bike, size M frame. Aluminum frame, 29 inch wheels. Perfect for Timor trails.', 650.00, 'USD', 'good', 'Dili', -8.5569, 125.5603, 'Bruno til', '77001919', '+670', 'bike.sale.tl@gmail.com', 'trek,mountain bike,cycling,sports,trails', 45, 15, 678, 1750000000, NULL, 0, NULL, '{"brand": "Trek", "model": "Marlin 7", "size": "M", "wheels": "29 inch"}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-sale-tv-1', 'LG 55 inch Smart TV - 4K', 'lg-55-inch-smart-tv-4k', 'user-19', 'electronics', 'published', 'LG 55 inch 4K Smart TV. WebOS, built-in WiFi, HDR. Perfect condition with original remote and stand.', 550.00, 'USD', 'good', 'Dili', -8.5569, 125.5603, 'Maria til', '77002020', '+670', 'tv.sale.tl@gmail.com', 'lg,smart tv,55 inch,4k,television', 56, 23, 890, 1750000000, NULL, 1, 1750000000, '{"brand": "LG", "size": "55 inch", "resolution": "4K", "smartTV": true}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-sale-sandalwood-1', 'Sandalwood Carving - Traditional Art', 'sandalwood-carving-traditional', 'user-20', 'arts', 'published', 'Authentic Timorese sandalwood carving. Traditional crocodile design, hand-crafted by local artisan. Certificate of authenticity included.', 350.00, 'USD', 'new', 'Arte Moris, Dili', -8.4789, 125.5890, 'Rosa til', '77002121', '+670', 'art.tl@gmail.com', 'sandalwood,carving,traditional,art,crocodile', 67, 34, 1120, 1750000000, NULL, 0, NULL, '{"material": "sandalwood", "style": "traditional", "origin": "Timor-Leste"}', 1700000000, 1750000000);

-- Services (5)
INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-service-photo-1', 'Wedding Photography - Full Day Coverage', 'wedding-photography-full-day-dili', 'user-21', 'photography', 'published', 'Professional wedding photographer with 8 years experience. Full day coverage, 500+ edited photos, 2 photographers.', 800.00, 'USD', NULL, 'Dili', -8.5569, 125.5603, 'Roberto til', '77002222', '+670', 'photo.tl@gmail.com', 'wedding,photography,professional,events,coverage', 89, 45, 1560, 1750000000, NULL, 1, 1750000000, '{"type": "event", "coverage": "full day", "photos": "500+", "photographers": 2}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-service-plumber-1', 'Professional Plumbing Service', 'professional-plumbing-service-dili', 'user-22', 'home-repair', 'published', 'Licensed plumber for all residential and commercial work. Piping, installation, repairs, and emergency service available.', 50.00, 'USD/hour', NULL, 'Dili', -8.5569, 125.5603, 'Afonso til', '77002323', '+670', 'plumber.dili@gmail.com', 'plumber,plumbing,repair,installation,emergency', 123, 56, 2340, 1750000000, NULL, 0, NULL, '{"service": "repair", "emergency": true, "licensed": true}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-service-tutor-1', 'Math & Science Tutor - Home Visits', 'math-science-tutor-home-visits', 'user-23', 'tutoring', 'published', 'Experienced tutor for primary and secondary students. Math, Physics, Chemistry. Home visits or online sessions available.', 25.00, 'USD/hour', NULL, 'Dili', -8.5569, 125.5603, 'Dr. Fatima til', '77002424', '+670', 'tutor.tl@gmail.com', 'tutor,math,physics,chemistry,education', 67, 34, 1230, 1750000000, NULL, 0, NULL, '{"subjects": ["math", "physics", "chemistry"], "level": "primary-secondary", "online": true}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-service-cleaning-1', 'Deep Cleaning Service - Homes & Offices', 'deep-cleaning-service-dili', 'user-24', 'cleaning', 'published', 'Professional deep cleaning for homes and offices. Including windows, carpets, upholstery. Eco-friendly products used.', 80.00, 'USD', NULL, 'Dili', -8.5569, 125.5603, 'Julia til', '77002525', '+670', 'clean.tl@gmail.com', 'cleaning,deep clean,house,office,professional', 89, 45, 1780, 1750000000, NULL, 0, NULL, '{"type": "deep cleaning", "ecoFriendly": true, "includes": ["windows", "carpets", "upholstery"]}', 1700000000, 1750000000);

INSERT INTO listings (id, title, slug, owner_id, category_id, status, description, price_amount, price_unit, condition, location, location_lat, location_lng, contact_name, contact_number, country_code, email, tags, likes, saves, views, expires_at, last_renewed_at, featured, featured_until, extra_data, created_at, updated_at) VALUES ('listing-service-moving-1', 'Moving & Relocation Service', 'moving-relocation-service-dili', 'user-25', 'moving', 'published', 'Complete moving service: packing, loading, transport, unloading. Local and long distance. Free quote on request.', 150.00, 'USD', NULL, 'Dili', -8.5569, 125.5603, 'Jose til', '77002626', '+670', 'moving.tl@gmail.com', 'moving,relocation,transport,pack,delivery', 56, 23, 890, 1750000000, NULL, 0, NULL, '{"service": "full service", "includes": ["packing", "loading", "transport", "unloading"]}', 1700000000, 1750000000);