-- Non-Profits Seed Data (10 entries)
-- TimorUp 2026-05-21

INSERT INTO non_profits (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, created_at, updated_at) VALUES ('ngo-hopital-bairo-pite', 'Hospital Bairo Pite', 'hospital-bairo-pite', 'ngo-admin-1', 'healthcare', 'published', 'Dr. Dan Silva', '77001234', '+670', 1999, 'info@hbp-tl.org', 'Bairo Pite, Dili', -8.5569, 125.5603, 'Mon-Sat: 8AM-5PM', 'Community-run hospital providing affordable healthcare to all Timorese. Services include emergency care, maternal health, and general medicine.', 'healthcare,hospital,medical,community', 456, 123, 5670, 'https://www.hbp-tl.org', 1, '{"facebook": "HospitalBairoPite", "instagram": "@hbptl"}', 1700000000, 1750000000);

INSERT INTO non_profits (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, created_at, updated_at) VALUES ('ngo-maluk-timor', 'Maluk Timor', 'maluk-timor', 'ngo-admin-2', 'healthcare', 'published', 'Dr. Joanita', '77002345', '+670', 2010, 'contact@maluktimor.org', 'Target, Dili', -8.5512, 125.5645, 'Mon-Fri: 8AM-4PM', 'Heart health organization specializing in cardiology and cardiovascular care for Timor-Leste.', 'health,cardiology,heart,medical', 234, 89, 2890, 'https://maluktimor.org', 1, '{"instagram": "@maluktimor", "facebook": "MalukTimor"}', 1700000000, 1750000000);

INSERT INTO non_profits (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, created_at, updated_at) VALUES ('ngo-fundasaun-cheia', 'Fundasaun Cheia', 'fundasaun-cheia', 'ngo-admin-3', 'education', 'published', 'Ana Belo', '77003456', '+670', 2008, 'info@fundasauncheira.tl', 'Lospalos', -8.5891, 126.9878, 'Mon-Fri: 7AM-5PM', 'Non-profit focused on education for children in remote areas. Programs include literacy, numeracy, and life skills training.', 'education,children,youth,remote areas', 178, 67, 1890, NULL, 1, '{"facebook": "FundasaunCheia"}', 1700000000, 1750000000);

INSERT INTO non_profits (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, created_at, updated_at) VALUES ('ngo-passaredo', 'Passaredo', 'passaredo', 'ngo-admin-4', 'education', 'published', 'Fr. Jose', '77004567', '+670', 1995, 'passaredo@tl.com', 'Aileu', -8.7306, 125.4044, 'Mon-Sat: 8AM-4PM', 'Foundation operating schools and vocational training centers across Timor-Leste.', 'education,vocational,schools,training', 289, 98, 3450, 'https://passaredo.org', 1, '{"facebook": "PassaredoTL"}', 1700000000, 1750000000);

INSERT INTO non_profits (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, created_at, updated_at) VALUES ('ngo-birds-timor', 'Timor-Leste Birds Program', 'birds-tl', 'ngo-admin-5', 'environment', 'published', 'Rui Oliveira', '77005678', '+670', 2015, 'info@birds-tl.org', 'Lospalos', -8.5891, 126.9878, 'Mon-Fri: 9AM-5PM', 'Conservation program protecting endangered bird species and their habitats in Timor-Leste.', 'environment,birds,conservation,wildlife', 134, 56, 1560, 'https://birds Timor.org', 0, '{"instagram": "@birdstimor"}', 1700000000, 1750000000);

INSERT INTO non_profits (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, created_at, updated_at) VALUES ('ngo-joan-gomes', 'Fundasaun Joan Gomes', 'fundasaun-joan-gomes', 'ngo-admin-6', 'agriculture', 'published', 'Luis da Costa', '77006789', '+670', 2012, 'fundasaunjgomes@gmail.com', 'Aileu', -8.7306, 125.4044, 'Mon-Fri: 8AM-4PM', 'Agricultural foundation promoting sustainable farming and food security in rural communities.', 'agriculture,farming,food security,rural', 167, 78, 2120, NULL, 0, '{"facebook": "FundasaunJoanGomes"}', 1700000000, 1750000000);

INSERT INTO non_profits (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, created_at, updated_at) VALUES ('ngo-feto-foin', 'Feto Foin', 'feto-foin', 'ngo-admin-7', 'women', 'published', 'Maria Ximenes', '77007890', '+670', 2005, 'fetufoin@gmail.com', 'Comoro, Dili', -8.5456, 125.5578, 'Mon-Fri: 9AM-5PM', 'Women organization empowering Timorese women through education, microfinance, and leadership programs.', 'women,empowerment,education,microfinance', 298, 145, 4230, NULL, 1, '{"instagram": "@fetofoin", "facebook": "FetoFoinTL"}', 1700000000, 1750000000);

INSERT INTO non_profits (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, created_at, updated_at) VALUES ('ngo-moris-fuin', 'Moris Fuin', 'moris-fuin', 'ngo-admin-8', 'community', 'published', 'Paulo Gusmao', '77008901', '+670', 2018, 'moris.fuin.tl@gmail.com', 'Viqueque', -8.8612, 126.3512, 'Mon-Sat: 8AM-5PM', 'Community development organization focused on youth empowerment and cultural preservation.', 'youth,community,culture,development', 89, 34, 980, NULL, 0, '{"facebook": "MorisFuin"}', 1700000000, 1750000000);

INSERT INTO non_profits (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, created_at, updated_at) VALUES ('ngo-habilitas', 'Habilitas Timor-Leste', 'habilitas-tl', 'ngo-admin-9', 'disability', 'published', 'Tomas Soares', '77009012', '+670', 2007, 'habilitas.tl@gmail.com', 'Bemori, Dili', -8.5234, 125.5432, 'Mon-Fri: 8AM-5PM', 'Organization advocating for and supporting people with disabilities in Timor-Leste.', 'disability,inclusion,rights,support', 234, 98, 2780, 'https://habilitastl.org', 1, '{"facebook": "HabilitasTL", "instagram": "@habilitastl"}', 1700000000, 1750000000);

INSERT INTO non_profits (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, created_at, updated_at) VALUES ('ngo-kdadatak', 'Kdadatak Foundation', 'kdadatak', 'ngo-admin-10', 'social-services', 'published', 'Fernanda til', '77000123', '+670', 2014, 'kdadatak.foundation@gmail.com', 'Lospalos', -8.5891, 126.9878, 'Mon-Fri: 8AM-4PM', 'Foundation supporting vulnerable children and families through social services and community programs.', 'children,family,social services,vulnerable', 156, 67, 1890, NULL, 0, '{"facebook": "KdadatakFoundation"}', 1700000000, 1750000000);