-- Products Seed Data (36 products for 18 businesses)
-- TimorUp 2026-05-21

-- Café Timor products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-cafe-espresso', 'biz-cafe-timor', 'coffee-drinks', 'Espresso', 'espresso', 'Single shot of Timor-Leste finest arabica coffee', 'product', 1.50, 'USD', '{"size": "small", "caffeine": "medium", "origin": "Ermera"}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-cafe-cold-brew', 'biz-cafe-timor', 'coffee-drinks', 'Cold Brew', 'cold-brew', '24-hour steeped cold brew, smooth and refreshing', 'product', 3.00, 'USD', '{"size": "large", "caffeine": "high", "served": "iced"}', '[]', 1, 1, 2, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-cafe-pastries', 'biz-cafe-timor', 'bakery', 'Fresh Pastries', 'fresh-pastries', 'Assorted freshly baked pastries and croissants', 'product', 2.50, 'USD', '{"type": "bakery", "freshlyBaked": true}', '[]', 0, 1, 3, 1700000000, 1750000000);

-- Warung Nazar products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-warung-bife-sufe', 'biz-warung-nazar', 'timorese-dishes', 'Bife Sufe', 'bife-sufe', 'Traditional Timorese beef in coconut sauce', 'product', 5.00, 'USD', '{"cuisine": "Timorese", "spiceLevel": "medium", "serves": 1}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-warung-fish-curry', 'biz-warung-nazar', 'timorese-dishes', 'Curry Fish', 'curry-fish', 'Fresh fish curry with local vegetables', 'product', 6.00, 'USD', '{"cuisine": "Timorese", "fish": "local catch", "spiceLevel": "hot"}', '[]', 1, 1, 2, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-warung-combo', 'biz-warung-nazar', 'meal-deals', 'Rice Plate Combo', 'rice-plate-combo', 'Rice with choice of meat, vegetables, and soup', 'product', 4.00, 'USD', '{"includes": ["rice", "protein", "veggies", "soup"]}', '[]', 0, 1, 3, 1700000000, 1750000000);

-- Burger King Timor products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-bk-whopper', 'biz-burger-king-dili', 'burgers', 'Whopper', 'whopper', 'Flame-grilled beef patty with fresh toppings', 'product', 6.50, 'USD', '{"calories": 657, "protein": "beef", "allergens": ["gluten", "dairy"]}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-bk-chicken', 'biz-burger-king-dili', 'chicken', 'Crispy Chicken Sandwich', 'crispy-chicken', 'Crispy breaded chicken with mayo and lettuce', 'product', 5.50, 'USD', '{"calories": 490, "protein": "chicken"}', '[]', 0, 1, 2, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-bk-combo', 'biz-burger-king-dili', 'meal-deals', 'Value Meal', 'value-meal', 'Burger + fries + drink', 'product', 9.00, 'USD', '{"includes": ["burger", "fries", "drink"]}', '[]', 1, 1, 3, 1700000000, 1750000000);

-- Hotel Timor products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-hotel-standard', 'biz-hotel-timor', 'rooms', 'Standard Room', 'standard-room', 'Comfortable room with AC, WiFi, and sea view', 'product', 80.00, 'USD/night', '{"bed": "double", "capacity": 2, "amenities": ["AC", "WiFi", "TV", "safe"]}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-hotel-suite', 'biz-hotel-timor', 'rooms', 'Ocean Suite', 'ocean-suite', 'Luxury suite with panoramic ocean view and balcony', 'product', 150.00, 'USD/night', '{"bed": "king", "capacity": 2, "amenities": ["AC", "WiFi", "minibar", "balcony", "jacuzzi"]}', '[]', 1, 1, 2, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-hotel-conference', 'biz-hotel-timor', 'services', 'Conference Room Rental', 'conference-room', 'Fully equipped conference room for meetings and events', 'service', 200.00, 'USD/day', '{"capacity": 50, "equipment": ["projector", "whiteboard", "sound system"]}', '[]', 0, 1, 3, 1700000000, 1750000000);

-- Guesthouse Santa Cruz products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-gh-dorm', 'biz-guesthouse-santa', 'rooms', 'Dormitory Bed', 'dormitory-bed', 'Shared dorm room with 4 beds, shared bathroom', 'product', 15.00, 'USD/night', '{"bed": "single", "capacity": 1, "shared": true}', '[]', 0, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-gh-private', 'biz-guesthouse-santa', 'rooms', 'Private Room', 'private-room', 'Private room with en-suite bathroom and fan', 'product', 25.00, 'USD/night', '{"bed": "double", "capacity": 2, "bathroom": "ensuite", "fan": true}', '[]', 1, 1, 2, 1700000000, 1750000000);

-- Timor Tech Solutions products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-tt-web-dev', 'biz-timor-tech', 'it-services', 'Website Development', 'website-development', 'Professional website design and development', 'service', 500.00, 'USD/project', '{"duration": "2-4 weeks", "pages": "up to 10", "includes": ["design", "development", "hosting setup"]}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-tt-consulting', 'biz-timor-tech', 'it-services', 'IT Consulting', 'it-consulting', 'Expert IT advice and system optimization', 'service', 75.00, 'USD/hour', '{"duration": "per hour", "remote": true}', '[]', 0, 1, 2, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-tt-support', 'biz-timor-tech', 'it-services', 'Tech Support Package', 'tech-support-package', 'Monthly IT support and maintenance', 'subscription', 200.00, 'USD/month', '{"hours": 10, "remoteSupport": true, "priority": "normal"}', '[]', 0, 1, 3, 1700000000, 1750000000);

-- Phone World Timor products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-pw-iphone-15', 'biz-phone-world', 'phones', 'iPhone 15', 'iphone-15', 'Latest iPhone with full warranty', 'product', 999.00, 'USD', '{"storage": "128GB", "color": "Black", "warranty": "1 year"}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-pw-samsung-s24', 'biz-phone-world', 'phones', 'Samsung S24 Ultra', 'samsung-s24-ultra', 'Samsung flagship with AI features', 'product', 1099.00, 'USD', '{"storage": "256GB", "color": "Titanium Gray", "warranty": "1 year"}', '[]', 1, 1, 2, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-pw-repair', 'biz-phone-world', 'repair-services', 'Screen Repair', 'screen-repair', 'Professional screen replacement for all brands', 'service', 30.00, 'USD', '{"warranty": "3 months", "original": true}', '[]', 0, 1, 3, 1700000000, 1750000000);

-- Timor Dental Clinic products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-dental-checkup', 'biz-dental-clinic', 'dental-services', 'Dental Checkup', 'dental-checkup', 'Complete oral examination and consultation', 'service', 20.00, 'USD', '{"duration": "30 min", "includes": ["examination", "x-ray", "consultation"]}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-dental-cleaning', 'biz-dental-clinic', 'dental-services', 'Teeth Cleaning', 'teeth-cleaning', 'Professional teeth cleaning and polishing', 'service', 35.00, 'USD', '{"duration": "45 min", "includes": ["cleaning", "polishing", "fluoride"]}', '[]', 0, 1, 2, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-dental-filling', 'biz-dental-clinic', 'dental-services', 'Tooth Filling', 'tooth-filling', 'Composite filling for cavities', 'service', 50.00, 'USD', '{"material": "composite", "color": "tooth-colored"}', '[]', 0, 1, 3, 1700000000, 1750000000);

-- Pharma Plus Dili products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-pharma-paracetamol', 'biz-pharma-plus', 'medicines', 'Paracetamol 500mg', 'paracetamol-500mg', 'Pain reliever and fever reducer', 'product', 2.50, 'USD', '{"dosage": "500mg", "quantity": "20 tablets", "generic": true}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-pharma-vitamins', 'biz-pharma-plus', 'health-products', 'Multivitamin Pack', 'multivitamin-pack', 'Daily vitamin supplements for immune support', 'product', 15.00, 'USD', '{"duration": "30 days", "dosage": "1 daily"}', '[]', 0, 1, 2, 1700000000, 1750000000);

-- Fitness First Timor products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-gym-day-pass', 'biz-fit-gym', 'fitness', 'Day Pass', 'day-pass', 'Single day access to all gym facilities', 'ticket', 5.00, 'USD', '{"validity": "1 day", "includes": ["all equipment", "locker"]}', '[]', 0, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-gym-monthly', 'biz-fit-gym', 'fitness', 'Monthly Membership', 'monthly-membership', 'Unlimited gym access for 30 days', 'subscription', 50.00, 'USD/month', '{"validity": "30 days", "includes": ["all equipment", "group classes", "locker"]}', '[]', 1, 1, 2, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-gym-personal', 'biz-fit-gym', 'personal-training', 'Personal Training Session', 'personal-training', 'One-on-one training with certified instructor', 'service', 30.00, 'USD/session', '{"duration": "60 min", "includes": ["assessment", "program design"]}', '[]', 0, 1, 3, 1700000000, 1750000000);

-- English Learning Center Timor products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-english-conversation', 'biz-english-center', 'language-courses', 'Conversation Class', 'conversation-class', 'Weekly conversation practice for intermediate learners', 'subscription', 80.00, 'USD/month', '{"sessions": 4, "duration": "60 min each", "level": "intermediate"}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-english-ielts', 'biz-english-center', 'language-courses', 'IELTS Preparation', 'ielts-preparation', 'Comprehensive IELTS test preparation course', 'subscription', 200.00, 'USD/month', '{"duration": "8 weeks", "includes": ["materials", "mock tests", "feedback"]}', '[]', 1, 1, 2, 1700000000, 1750000000);

-- Salon Maria products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-salon-haircut', 'biz-salon-maria', 'hair-services', 'Women''s Haircut', 'womens-haircut', 'Professional haircut and styling', 'service', 15.00, 'USD', '{"duration": "45 min", "includes": ["wash", "cut", "style"]}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-salon-color', 'biz-salon-maria', 'hair-services', 'Hair Coloring', 'hair-coloring', 'Full hair coloring with professional products', 'service', 45.00, 'USD', '{"duration": "2 hours", "type": "permanent"}', '[]', 0, 1, 2, 1700000000, 1750000000);

-- Timor Auto Repair products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-auto-oil-change', 'biz-auto-repair', 'vehicle-maintenance', 'Oil Change', 'oil-change', 'Full oil and filter change service', 'service', 25.00, 'USD', '{"duration": "30 min", "oil": "synthetic blend"}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-auto-tire', 'biz-auto-repair', 'vehicle-maintenance', 'Tire Replacement', 'tire-replacement', 'Quality tire replacement and balancing', 'product', 80.00, 'USD', '{"brand": "Michelin", "size": "185/65R15"}', '[]', 0, 1, 2, 1700000000, 1750000000);

-- Supermercado Matavia products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-matavia-rice-5kg', 'biz-supermarket-matavia', 'groceries', 'Premium Rice 5kg', 'premium-rice-5kg', 'High quality local rice, 5kg bag', 'product', 12.00, 'USD', '{"weight": "5kg", "origin": "Timor-Leste", "type": "premium"}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-matavia-cooking-oil', 'biz-supermarket-matavia', 'groceries', 'Cooking Oil 2L', 'cooking-oil-2l', 'Palm cooking oil, 2 liters', 'product', 5.50, 'USD', '{"volume": "2L", "type": "palm oil"}', '[]', 0, 1, 2, 1700000000, 1750000000);

-- Timor Souvenir Shop products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-souvenir-tais', 'biz-toko-souvenir', 'handicrafts', 'Traditional Tais Cloth', 'traditional-tais-cloth', 'Hand-woven authentic Timorese textile', 'product', 85.00, 'USD', '{"size": "1m x 2m", "material": "cotton", "origin": "Aileu"}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-souvenir-wood-carving', 'biz-toko-souvenir', 'handicrafts', 'Wooden carved statue', 'wooden-carved-statue', 'Traditional Timorese wood carving', 'product', 45.00, 'USD', '{"height": "30cm", "wood": "sandelwood", "style": "traditional"}', '[]', 0, 1, 2, 1700000000, 1750000000);

-- Banca Timor products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-banca-micro-loan', 'biz-bancatimu', 'financial-services', 'Micro Business Loan', 'micro-business-loan', 'Small business financing up to $5,000', 'service', NULL, NULL, '{"minAmount": 500, "maxAmount": 5000, "term": "6-24 months", "rate": "12% annual"}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-banca-savings', 'biz-bancatimu', 'financial-services', 'Savings Account', 'savings-account', 'Basic savings account with competitive interest', 'service', NULL, NULL, '{"minBalance": 10, "interestRate": "3% annually", "features": ["ATM card", "mobile banking"]}', '[]', 0, 1, 2, 1700000000, 1750000000);

-- Aqua Timor products
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-water-20L', 'biz-water-timor', 'water', '20L Bottle', '20l-bottle', 'Premium bottled water, 20 liter', 'product', 3.00, 'USD', '{"volume": "20L", "type": "premium"}', '[]', 1, 1, 1, 1700000000, 1750000000);
INSERT INTO products (id, business_id, category_id, title, slug, description, product_type, price_amount, price_unit, specifications, images, featured, active, sort_order, created_at, updated_at) VALUES ('prod-water-delivery', 'biz-water-timor', 'services', 'Water Delivery Service', 'water-delivery', 'Monthly water delivery to your home or office', 'subscription', 25.00, 'USD/month', '{"delivery": "monthly", "bottles": 4, "includes": "stand"}', '[]', 0, 1, 2, 1700000000, 1750000000);