-- Public Sectors Seed Data (10 entries)
-- TimorUp 2026-05-21

INSERT INTO public_sectors (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, government_data, created_at, updated_at) VALUES ('gov-ministerio-financas', 'Ministry of Finance', 'ministry-of-finance-tl', 'gov-admin-1', 'ministries', 'published', 'Servico', '77001000', '+670', 2002, 'info@mof.gov.tl', 'Palacio do Governo, Dili', -8.5569, 125.5603, 'Mon-Fri: 8:30AM-5PM', 'Responsible for national budget, treasury, tax policy, and financial regulation.', 'government,finance,budget,tax', 345, 89, 4560, 'https://www.gov.tl/mof', 1, '{"facebook": "MinisterioFinancasTL"}', '{"department": "Ministry", "serviceTypes": ["Tax Registration", "Business Licensing", "Budget Information"], "jurisdiction": "National"}', 1700000000, 1750000000);

INSERT INTO public_sectors (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, government_data, created_at, updated_at) VALUES ('gov-ministerio-saude', 'Ministry of Health', 'ministry-of-health-tl', 'gov-admin-2', 'ministries', 'published', 'Geral', '77002000', '+670', 2002, 'contact@ms.gov.tl', 'Palacio do Governo, Dili', -8.5569, 125.5603, 'Mon-Fri: 8AM-5PM', 'Overseeing public health services, hospitals, and health policy across Timor-Leste.', 'government,health,medical,public services', 567, 234, 6780, 'https://www.gov.tl/ms', 1, '{"facebook": "MinisterioSaudeTL"}', '{"department": "Ministry", "serviceTypes": ["Health Services", "Vaccination Programs", "Hospital Information"], "jurisdiction": "National"}', 1700000000, 1750000000);

INSERT INTO public_sectors (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, government_data, created_at, updated_at) VALUES ('gov-ministerio-educacao', 'Ministry of Education', 'ministry-of-education-tl', 'gov-admin-3', 'ministries', 'published', 'Geral', '77003000', '+670', 2002, 'info@me.gov.tl', 'Palacio do Governo, Dili', -8.5569, 125.5603, 'Mon-Fri: 8AM-5PM', 'Managing national education system, schools, curriculum, and teacher training programs.', 'government,education,schools,curriculum', 489, 178, 5890, 'https://www.gov.tl/me', 1, '{"facebook": "MinisterioEducacaoTL"}', '{"department": "Ministry", "serviceTypes": ["School Registration", "Scholarships", "Curriculum Information"], "jurisdiction": "National"}', 1700000000, 1750000000);

INSERT INTO public_sectors (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, government_data, created_at, updated_at) VALUES ('gov-pntl', 'National Police Timor-Leste (PNTL)', 'pntl-timor-leste', 'gov-admin-4', 'police', 'published', 'Estasaun Central', '77003333', '+670', 2000, 'pntl.gov.tl@gmail.com', 'Comoro, Dili', -8.5456, 125.5578, '24/7', 'Timor-Leste national police force providing law enforcement and public safety services.', 'police,security,law enforcement,emergency', 678, 156, 8900, 'https://www.pntl.gov.tl', 1, '{"facebook": "PNTL Timor"}', '{"department": "Security", "serviceTypes": ["Crime Reporting", "Emergency Response", "Traffic Management"], "jurisdiction": "National"}', 1700000000, 1750000000);

INSERT INTO public_sectors (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, government_data, created_at, updated_at) VALUES ('gov-defesa-civil', 'Civil Protection Service', 'civil-protection-tl', 'gov-admin-5', 'emergency', 'published', 'Centro Coordenacao', '77003334', '+670', 2008, 'protecao.civil.gov.tl@gmail.com', 'Dili', -8.5569, 125.5603, '24/7', 'Managing disaster response, emergency coordination, and civil protection services.', 'emergency,disaster response,civil protection,safety', 234, 89, 3450, NULL, 1, '{"facebook": "ProtecaoCivilTL"}', '{"department": "Emergency Services", "serviceTypes": ["Disaster Response", "Emergency Coordination", "Evacuation"], "jurisdiction": "National"}', 1700000000, 1750000000);

INSERT INTO public_sectors (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, government_data, created_at, updated_at) VALUES ('gov-migracao', 'Directorate of Migration', 'migration-directorate-tl', 'gov-admin-6', 'immigration', 'published', 'Recepcao', '77003335', '+670', 2002, 'migracao@gov.tl', 'Avenida dos Direitos Humanos, Dili', -8.5612, 125.5634, 'Mon-Fri: 8AM-4PM', 'Managing passport issuance, visa applications, and immigration services.', 'immigration,passport,visa,documentation', 456, 134, 5670, 'https://www.gov.tl/migracao', 1, '{}', '{"department": "Immigration", "serviceTypes": ["Passport", "Visa", "Work Permit", "Residency"], "jurisdiction": "National"}', 1700000000, 1750000000);

INSERT INTO public_sectors (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, government_data, created_at, updated_at) VALUES ('gov-ministerio-justica', 'Ministry of Justice', 'ministry-of-justice-tl', 'gov-admin-7', 'justice', 'published', 'Geral', '77004000', '+670', 2002, 'info@mj.gov.tl', 'Palacio do Governo, Dili', -8.5569, 125.5603, 'Mon-Fri: 8:30AM-5PM', 'Responsible for legal affairs, prison services, land and property registration.', 'government,justice,legal,registry', 345, 98, 4230, 'https://www.gov.tl/mj', 1, '{"facebook": "MinisterioJusticaTL"}', '{"department": "Ministry", "serviceTypes": ["Land Registry", "Company Registration", "Notary Services"], "jurisdiction": "National"}', 1700000000, 1750000000);

INSERT INTO public_sectors (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, government_data, created_at, updated_at) VALUES ('gov-servico-receita', 'Tax and Revenue Service', 'tax-revenue-service-tl', 'gov-admin-8', 'tax', 'published', 'Atendimento', '77005555', '+670', 2003, 'contact@srt.gov.tl', 'Edificio Financeiro, Dili', -8.5569, 125.5603, 'Mon-Fri: 8AM-4PM', 'Collecting taxes, managing customs, and revenue enforcement for Timor-Leste.', 'government,tax,customs,revenue', 289, 67, 3890, 'https://www.gov.tl/srt', 1, '{}', '{"department": "Revenue", "serviceTypes": ["Income Tax", "VAT", "Customs", "Excise"], "jurisdiction": "National"}', 1700000000, 1750000000);

INSERT INTO public_sectors (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, government_data, created_at, updated_at) VALUES ('gov-servico-emprego', 'National Employment Service', 'national-employment-service-tl', 'gov-admin-9', 'employment', 'published', 'Centro Emprego', '77006666', '+670', 2010, 'emprego@gov.tl', 'Lacar Lecidere, Dili', -8.5590, 125.5620, 'Mon-Fri: 8AM-4PM', 'Job placement services, vocational training, and labor market information.', 'government,employment,jobs,training,labor', 456, 189, 5230, 'https://www.gov.tl/employment', 1, '{"facebook": "Emprego Timor"}', '{"department": "Labor", "serviceTypes": ["Job Search", "Training", "Career Counseling"], "jurisdiction": "National"}', 1700000000, 1750000000);

INSERT INTO public_sectors (id, title, slug, owner_id, category_id, status, contact_name, contact_number, country_code, year_of_establishment, email, address, location_lat, location_lng, opening_hours, about_us, tags, likes, saves, views, registration_url, verified_badge, social_links, government_data, created_at, updated_at) VALUES ('gov-camara-municipal-dili', 'Dili Municipal Authority', 'dili-municipal-authority', 'gov-admin-10', 'municipal', 'published', 'Gabinete', '77007777', '+670', 2004, 'cmdili@gov.tl', 'Dili Municipal Building', -8.5569, 125.5603, 'Mon-Fri: 8AM-5PM', 'Managing municipal services for Dili: waste collection, roads, permits, and local administration.', 'government,municipal,dili,local government,public services', 567, 234, 6890, 'https://www.gov.tl/dili', 1, '{"facebook": "CamaraDili"}', '{"department": "Municipal", "serviceTypes": ["Permits", "Waste Collection", "Road Maintenance", "Local Events"], "jurisdiction": "Dili Municipality"}', 1700000000, 1750000000);